import { ENEMIES } from './content';
import { Rng } from './rng';
import type { EnemyKind, GameState, ItemKind, Point, Tile } from './types';
import { at, updateVisibility } from './world';

const dirs=[[1,0],[-1,0],[0,1],[0,-1]] as const;
const d=(a:Point,b:Point)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
const key=(p:Point)=>`${p.x},${p.y}`;

function clearFloor(s:GameState,p:Point){const t=at(s,p);return !!t&&t.kind==='floor'&&!t.fixture&&!t.blocks}
function reserved(s:GameState,p:Point){if(p.x===s.player.x&&p.y===s.player.y)return true;if(s.enemies.some(e=>e.x===p.x&&e.y===p.y))return true;if(s.items.some(i=>i.x===p.x&&i.y===p.y))return true;return at(s,p)?.kind==='stairs'}
function interiorCandidate(s:GameState,p:Point){const t=at(s,p);if(!t||t.kind!=='floor'||t.fixture||t.blocks||reserved(s,p)||d(p,s.player)<7)return false;if(!dirs.every(([dx,dy])=>{const n=at(s,{x:p.x+dx,y:p.y+dy});return !!n&&n.kind!=='wall'}))return false;if(s.enemies.some(e=>d(e,p)<3)||s.items.some(i=>d(i,p)<2))return false;for(let y=Math.max(0,p.y-1);y<=Math.min(s.height-1,p.y+1);y++)for(let x=Math.max(0,p.x-1);x<=Math.min(s.width-1,p.x+1);x++){const q=at(s,{x,y});if(q?.kind==='stairs'||q?.fixture==='brass-gate')return false}return true}
function chooseCenter(s:GameState,rng:Rng,rooms:string[]):Point|undefined{const preferred:Point[]=[];const fallback:Point[]=[];for(let y=1;y<s.height-1;y++)for(let x=1;x<s.width-1;x++){const p={x,y};if(!interiorCandidate(s,p))continue;const room=at(s,p)?.room??'';(rooms.includes(room)?preferred:fallback).push(p)}const pool=preferred.length?preferred:fallback;if(!pool.length)return undefined;return pool[rng.int(0,pool.length-1)]}
function mutateAround(s:GameState,c:Point,kind:Tile['kind'],includeCenter=false){for(const [dx,dy] of dirs){const p={x:c.x+dx,y:c.y+dy},t=at(s,p);if(t&&clearFloor(s,p)&&!reserved(s,p)){t.kind=kind;t.variant=2}}if(includeCenter){const t=at(s,c);if(t&&clearFloor(s,c)){t.kind=kind;t.variant=2}}}
function fixture(s:GameState,p:Point,name:NonNullable<Tile['fixture']>,blocks=true,state=0){const t=at(s,p);if(!t||t.kind==='wall'||reserved(s,p))return false;t.fixture=name;t.blocks=blocks;t.state=state;return true}
function safeNearby(s:GameState,c:Point,radius=2){const out:Point[]=[];for(let r=1;r<=radius;r++)for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++){if(Math.abs(dx)+Math.abs(dy)!==r)continue;const p={x:c.x+dx,y:c.y+dy};if(clearFloor(s,p)&&!reserved(s,p))out.push(p)}return out}
function drop(s:GameState,c:Point,kind:ItemKind,id:string){const p=safeNearby(s,c,3).find(q=>!s.items.some(i=>i.x===q.x&&i.y===q.y)&&!s.enemies.some(e=>e.x===q.x&&e.y===q.y));if(p)s.items.push({id,kind,x:p.x,y:p.y})}
function spawn(s:GameState,c:Point,kind:EnemyKind,id:string){const p=safeNearby(s,c,3).find(q=>!s.items.some(i=>i.x===q.x&&i.y===q.y)&&!s.enemies.some(e=>e.x===q.x&&e.y===q.y));if(p)s.enemies.push({id,kind,x:p.x,y:p.y,hp:ENEMIES[kind].hp,cooldown:1})}
function noteSeed(s:GameState,c:Point,signature:number){const t=at(s,c);if(t)t.variant=(t.variant&7)|(signature<<3)}

function stageOne(s:GameState,rng:Rng,c:Point,variant:number){if(variant===0){fixture(s,c,'barrel',true,1);mutateAround(s,c,'oil');drop(s,c,'red-phial','special-red');spawn(s,c,'distiller-rat','special-rat');noteSeed(s,c,1)}else if(variant===1){fixture(s,c,'fountain',true,1);mutateAround(s,c,'rune');drop(s,c,'neutralizer','special-neutralizer');const q=safeNearby(s,c,2)[0];if(q)fixture(s,q,'sealed-cache',true,0);noteSeed(s,c,2)}else{fixture(s,c,'incinerator',true,0);mutateAround(s,c,'glass');drop(s,c,'blue-tonic','special-tonic');spawn(s,c,'glass-mite','special-mite');noteSeed(s,c,3)}}
function stageTwo(s:GameState,rng:Rng,c:Point,variant:number){if(variant===0){fixture(s,c,'fountain',true,1);mutateAround(s,c,'brine');drop(s,c,'frost-salts','special-frost');spawn(s,c,'miasma-moth','special-moth');noteSeed(s,c,4)}else if(variant===1){fixture(s,c,'stall',true,2);mutateAround(s,c,'miasma');drop(s,c,'solvent','special-solvent');const q=safeNearby(s,c,2)[0];if(q)fixture(s,q,'sealed-cache',true,0);spawn(s,c,'homunculus','special-hom');noteSeed(s,c,5)}else{fixture(s,c,'transmuter',true,0);mutateAround(s,c,'crystal');drop(s,c,'black-catalyst','special-catalyst');spawn(s,c,'glass-sentinel','special-sentinel');noteSeed(s,c,6)}}
function stageThree(s:GameState,rng:Rng,c:Point,variant:number){if(variant===0){fixture(s,c,'valve',true,0);mutateAround(s,c,'brine');const steam=safeNearby(s,c,2).slice(0,2);for(const p of steam){const t=at(s,p);if(t&&clearFloor(s,p)){t.kind='steam';t.variant=3}}drop(s,c,'frost-salts','special-frost-3');spawn(s,c,'brine-warden','special-warden');noteSeed(s,c,7)}else if(variant===1){fixture(s,c,'crucible',true,0);mutateAround(s,c,'embers');drop(s,c,'amber-elixir','special-amber');spawn(s,c,'soot-sprite','special-soot');noteSeed(s,c,8)}else{fixture(s,c,'silver-mirror',true,0);mutateAround(s,c,'rune');drop(s,c,'black-catalyst','special-black-3');const q=safeNearby(s,c,2)[0];if(q)fixture(s,q,'sealed-cache',true,0);spawn(s,c,'glass-sentinel','special-sentinel-3');noteSeed(s,c,9)}}

export function applySpecialFeatures(s:GameState){const rng=new Rng((s.seed^Math.imul(s.districtStage,0x6d2b79f5)^0xa1c4e7)>>>0);const rooms=s.districtStage===1?['herbalist','distillery','glassworks','courtyard','underworks','sealed-shop']:s.districtStage===2?['dye-vats','counting-house','black-market','cistern','wayhouse','old-exchange']:['assay-lab','kiln-hall','old-mint','cooling-vault','master-lab','final-vault'];const c=chooseCenter(s,rng,rooms);if(!c)return;const variant=rng.int(0,2);if(s.districtStage===1)stageOne(s,rng,c,variant);else if(s.districtStage===2)stageTwo(s,rng,c,variant);else stageThree(s,rng,c,variant);updateVisibility(s)}

export function specialSignature(s:GameState){const signatures=new Set(['barrel:fuel','fountain:runes','incinerator:glass','fountain:brine','stall:miasma','transmuter:crystal','valve:brine','crucible:embers','silver-mirror:runes']);const found:string[]=[];for(let y=0;y<s.height;y++)for(let x=0;x<s.width;x++){const t=at(s,{x,y});if(!t?.fixture)continue;const nearby=dirs.map(([dx,dy])=>at(s,{x:x+dx,y:y+dy})?.kind);if(t.fixture==='barrel'&&nearby.includes('oil'))found.push('barrel:fuel');if(t.fixture==='fountain'&&nearby.includes('rune'))found.push('fountain:runes');if(t.fixture==='incinerator'&&nearby.includes('glass'))found.push('incinerator:glass');if(t.fixture==='fountain'&&nearby.includes('brine'))found.push('fountain:brine');if(t.fixture==='stall'&&nearby.includes('miasma'))found.push('stall:miasma');if(t.fixture==='transmuter'&&nearby.includes('crystal'))found.push('transmuter:crystal');if(t.fixture==='valve'&&nearby.includes('brine'))found.push('valve:brine');if(t.fixture==='crucible'&&nearby.includes('embers'))found.push('crucible:embers');if(t.fixture==='silver-mirror'&&nearby.includes('rune'))found.push('silver-mirror:runes')}return found.filter(x=>signatures.has(x)).sort().join('|')}
