import { ENEMIES } from './content';
import { Rng } from './rng';
import type { Enemy, GameState, ItemKind, Point, Tile } from './types';
import { at, updateVisibility } from './world';

const dist=(a:Point,b:Point)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
const dirs=[[1,0],[-1,0],[0,1],[0,-1]] as const;
const flammable=new Set<Tile['fixture']>(['crate','barrel','awning','herbs','planter','counter','table','cart','boards']);
const aimed=new Set<ItemKind>(['red-phial','salt-bomb','smoke-ampoule','black-catalyst']);

export function isAimedItem(kind:ItemKind){return aimed.has(kind)}
export function push(state:GameState,text:string,tone?:'good'|'bad'|'odd'){state.messages.push({text,tone});if(state.messages.length>9)state.messages.shift()}
function enemyAt(s:GameState,x:number,y:number){return s.enemies.find(e=>e.x===x&&e.y===y)}
function passable(s:GameState,x:number,y:number){const t=at(s,{x,y});return !!t&&t.kind!=='wall'&&!t.blocks}
function makeNoise(s:GameState,p:Point){s.noise.push({x:p.x,y:p.y});if(s.noise.length>6)s.noise.shift()}
function hasStatus(s:GameState,id:GameState['player']['statuses'][number]['id']){return s.player.statuses.some(st=>st.id===id)}
function addStatus(s:GameState,id:GameState['player']['statuses'][number]['id'],turns:number){const st=s.player.statuses.find(x=>x.id===id);if(st)st.turns=Math.max(st.turns,turns);else s.player.statuses.push({id,turns})}
function hurtPlayer(s:GameState,n:number,msg:string){const ward=hasStatus(s,'warded')?1:0;const dmg=Math.max(0,n-s.player.guard-ward);s.player.guard=0;s.player.hp-=dmg;push(s,`${msg} (${dmg})`,'bad');if(s.player.hp<=0){s.player.hp=0;s.over=true;push(s,'You die among the shuttered shops.','bad')}}
function hurtEnemy(s:GameState,e:Enemy,n:number){e.hp-=n;push(s,`${ENEMIES[e.kind].name} takes ${n}.`,'good');if(e.hp>0)return;s.enemies=s.enemies.filter(x=>x!==e);makeNoise(s,e);push(s,`${ENEMIES[e.kind].name} collapses.`,'good');if(e.kind==='glass-mite'){for(const [dx,dy] of dirs){const q={x:e.x+dx,y:e.y+dy},t=at(s,q);if(t&&t.kind==='floor'){t.kind='glass';t.variant=2}if(s.player.x===q.x&&s.player.y===q.y)hurtPlayer(s,2,'Glass splinters cut you')}}if(e.kind==='soot-sprite'){for(const [dx,dy] of dirs){const t=at(s,{x:e.x+dx,y:e.y+dy});if(t?.kind==='oil')ignite(t,4)}}}
function burnFixture(t:Tile){if(t.fixture&&flammable.has(t.fixture)){t.fixture=undefined;t.blocks=false;t.state=0}}
function ignite(t:Tile,turns=4){if(t.kind==='wall'||t.kind==='water')return;t.kind='fire';t.variant=Math.max(t.variant,turns);burnFixture(t)}
function neutralize(t:Tile){if(t.kind==='acid'||t.kind==='fire'||t.kind==='steam'){t.kind='sludge';t.variant=1}}
function explodeBarrel(s:GameState,p:Point){makeNoise(s,p);push(s,'A spirit barrel bursts with a flat copper boom.','odd');for(const [dx,dy] of [[0,0],...dirs] as const){const q={x:p.x+dx,y:p.y+dy},t=at(s,q);if(t)ignite(t,4);const e=enemyAt(s,q.x,q.y);if(e)hurtEnemy(s,e,5);if(s.player.x===q.x&&s.player.y===q.y)hurtPlayer(s,4,'Burning spirit washes over you')}}
function catalystBurst(s:GameState,p:Point){makeNoise(s,p);push(s,'The black catalyst answers the floor with a hard white flash.','odd');for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const q={x:p.x+dx,y:p.y+dy},t=at(s,q);if(!t||t.kind==='wall')continue;if(t.kind==='oil'||t.kind==='acid'||t.kind==='fire')ignite(t,5);else if(Math.abs(dx)+Math.abs(dy)<=1&&t.kind==='floor')t.kind='glass';const e=enemyAt(s,q.x,q.y);if(e)hurtEnemy(s,e,dx===0&&dy===0?8:4);if(s.player.x===q.x&&s.player.y===q.y)hurtPlayer(s,3,'The reaction catches you')}}
function spillVat(s:GameState,p:Point){push(s,'The vat skin splits. Green liquor crawls across the floor.','odd');makeNoise(s,p);for(const [dx,dy] of [[0,0],...dirs] as const){const t=at(s,{x:p.x+dx,y:p.y+dy});if(t&&t.kind!=='wall'){t.kind='acid';t.variant=2}}}

function environmentalTick(s:GameState){if(hasStatus(s,'bleeding'))hurtPlayer(s,1,'The cut keeps bleeding');const under=at(s,s.player);if(under?.kind==='acid')hurtPlayer(s,2,'Acid eats through your boots');if(under?.kind==='fire')hurtPlayer(s,3,'Flame catches your clothes');if(under?.kind==='steam')hurtPlayer(s,2,'Hot steam scalds you');if(under?.kind==='glass'){hurtPlayer(s,1,'Glass grinds underfoot');addStatus(s,'bleeding',3)}if(under?.kind==='sludge')addStatus(s,'sluggish',2);if(under?.kind==='rune'&&!hasStatus(s,'warded')){addStatus(s,'warded',4);push(s,'The chalkless sigil feels briefly warm beneath your sole.','odd')}for(const e of [...s.enemies]){const t=at(s,e);if(!t)continue;if(t.kind==='fire'&&e.kind!=='soot-sprite')hurtEnemy(s,e,3);else if(t.kind==='acid'){if(e.kind==='retort-leech')e.hp=Math.min(ENEMIES[e.kind].hp,e.hp+1);else hurtEnemy(s,e,1)}else if(t.kind==='steam'&&e.kind!=='soot-sprite')hurtEnemy(s,e,1)}const spreads:Point[]=[];for(let y=0;y<s.height;y++)for(let x=0;x<s.width;x++){const t=s.tiles[y*s.width+x];if(!t)continue;if(t.kind==='fire'){burnFixture(t);t.variant=Math.max(0,t.variant-1);for(const [dx,dy] of dirs){const n=at(s,{x:x+dx,y:y+dy});if(n?.kind==='oil')spreads.push({x:x+dx,y:y+dy})}if(t.variant===0)t.kind='floor'}else if(t.kind==='steam'){t.variant=Math.max(0,t.variant-1);if(t.variant===0)t.kind='floor'}}for(const p of spreads){const t=at(s,p);if(t)ignite(t,4)}}

function stepToward(s:GameState,e:Enemy,target:Point,rng:Rng){const choices=[...dirs].sort((a,b)=>{const pa={x:e.x+a[0],y:e.y+a[1]},pb={x:e.x+b[0],y:e.y+b[1]},ta=at(s,pa),tb=at(s,pb);const chalkA=e.kind==='vapor-hound'&&ta?.variant===15?7:0,chalkB=e.kind==='vapor-hound'&&tb?.variant===15?7:0;const fireA=ta?.kind==='fire'&&e.kind!=='soot-sprite'?6:0,fireB=tb?.kind==='fire'&&e.kind!=='soot-sprite'?6:0;return dist(pa,target)+chalkA+fireA-dist(pb,target)-chalkB-fireB+(rng.next()-.5)*.2});for(const [dx,dy] of choices){const x=e.x+dx,y=e.y+dy;if(!passable(s,x,y)||enemyAt(s,x,y)||(s.player.x===x&&s.player.y===y))continue;e.x=x;e.y=y;return}}
function nearestNoise(s:GameState,e:Enemy){return [...s.noise].sort((a,b)=>dist(a,e)-dist(b,e))[0]}
function enemyAware(s:GameState,e:Enemy){const d=dist(e,s.player),tile=at(s,e),scented=hasStatus(s,'marked'),heard=s.noise.some(n=>dist(n,e)<=10);return d<=2||!!tile?.visible||(scented&&d<=13)||heard}
function createHazardAtPlayer(s:GameState,rng:Rng){const t=at(s,s.player);if(!t||t.kind==='wall')return;const roll=rng.int(0,2);t.kind=roll===0?'acid':roll===1?'oil':'glass';t.variant=roll===2?2:3}
function enemyTurn(s:GameState,e:Enemy,rng:Rng){if(!s.enemies.includes(e)||s.over)return;if(!enemyAware(s,e)){const n=nearestNoise(s,e);if(n)stepToward(s,e,n,rng);return}const d=dist(e,s.player),def=ENEMIES[e.kind];if(e.kind==='vapor-hound'){if(e.telegraph){const p=e.telegraph;e.telegraph=undefined;if(p.x===s.player.x&&p.y===s.player.y)hurtPlayer(s,def.damage,'Corrosive vapor burns you');const t=at(s,p);if(t&&t.kind!=='wall'&&!t.blocks){t.kind='acid';t.variant=2}e.cooldown=3;return}if(e.cooldown<=0&&d<=6){e.telegraph={x:s.player.x,y:s.player.y};push(s,'The Vapor Hound lowers its head. A sour haze gathers around your feet.','bad');return}}if(e.kind==='gutter-alchemist'){if(e.telegraph){const p=e.telegraph;e.telegraph=undefined;if(p.x===s.player.x&&p.y===s.player.y)hurtPlayer(s,2,'A reagent flask bursts against you');createHazardAtPlayer(s,rng);makeNoise(s,p);e.cooldown=3;return}if(e.cooldown<=0&&d<=7){e.telegraph={x:s.player.x,y:s.player.y};push(s,'The Gutter Alchemist raises a cloudy bottle.','bad');return}}if(d===1){hurtPlayer(s,def.damage,`${def.name} hits you`);makeNoise(s,e);return}if(e.kind==='distiller-rat'){const nearFire=dirs.some(([dx,dy])=>at(s,{x:e.x+dx,y:e.y+dy})?.kind==='fire');if(nearFire){stepToward(s,e,{x:e.x+(e.x-s.player.x)*2,y:e.y+(e.y-s.player.y)*2},rng);return}}if(e.kind==='retort-leech'){const acidTargets:Point[]=[];for(let y=Math.max(0,e.y-4);y<=Math.min(s.height-1,e.y+4);y++)for(let x=Math.max(0,e.x-4);x<=Math.min(s.width-1,e.x+4);x++)if(at(s,{x,y})?.kind==='acid')acidTargets.push({x,y});const target=acidTargets.sort((a,b)=>dist(a,e)-dist(b,e))[0];if(target&&e.hp<ENEMIES[e.kind].hp){stepToward(s,e,target,rng);return}}if(e.kind==='brine-warden'){if(e.cooldown>0)return;e.cooldown=1}if(d<=10||hasStatus(s,'marked')||nearestNoise(s,e))stepToward(s,e,s.player,rng)}
function advance(s:GameState,rng:Rng){s.turn++;environmentalTick(s);const sluggish=hasStatus(s,'sluggish');for(const e of [...s.enemies]){e.cooldown=Math.max(0,e.cooldown-1);enemyTurn(s,e,rng)}if(sluggish&&!s.over){push(s,'The sludge drags at your boots.','bad');for(const e of [...s.enemies])if(enemyAware(s,e))enemyTurn(s,e,rng)}s.noise=[];for(const st of s.player.statuses)st.turns--;s.player.statuses=s.player.statuses.filter(x=>x.turns>0);updateVisibility(s)}

export function move(s:GameState,dx:number,dy:number){if(s.over)return;const rng=new Rng((s.seed+s.turn*2654435761)>>>0),x=s.player.x+dx,y=s.player.y+dy;if(!passable(s,x,y))return;const enemy=enemyAt(s,x,y);if(enemy){makeNoise(s,s.player);hurtEnemy(s,enemy,4)}else{s.player.x=x;s.player.y=y;const item=s.items.find(i=>i.x===x&&i.y===y);if(item){s.player.inventory.push(item.kind);s.items=s.items.filter(i=>i!==item);push(s,`Picked up ${item.kind.replaceAll('-',' ')}.`,'good')}const t=at(s,s.player);if(t?.kind==='stairs'){s.won=true;s.over=true;push(s,s.enemies.length?'You take the brass stair while the district remains awake behind you.':'The brass stair turns beneath your weight. The lower market is open.','odd')}}advance(s,rng)}
function throwTarget(s:GameState,target:Point,range=6):Point{let x=s.player.x,y=s.player.y;const tx=target.x,ty=target.y,dx=Math.abs(tx-x),sx=x<tx?1:-1,dy=-Math.abs(ty-y),sy=y<ty?1:-1;let err=dx+dy,steps=0,last={x,y};while(!(x===tx&&y===ty)&&steps<range){const e2=2*err;if(e2>=dy){err+=dy;x+=sx}if(e2<=dx){err+=dx;y+=sy}const t=at(s,{x,y});if(!t||t.kind==='wall')break;last={x,y};steps++;if(t.blocks||enemyAt(s,x,y))break}return last}
function useCopperKey(s:GameState):boolean{for(const [dx,dy] of dirs){const t=at(s,{x:s.player.x+dx,y:s.player.y+dy});if(!t)continue;if(t.fixture==='brass-gate'){t.blocks=false;t.fixture=undefined;push(s,'The copper key turns once. The brass gate folds into the wall.','good');return true}if(t.fixture==='sealed-cache'){t.fixture='cabinet';t.blocks=true;t.state=2;push(s,'The copper key opens the cache without waking its trap.','good');return true}}push(s,'No matching lock is within reach.');return false}
export function useItem(s:GameState,index:number,target:Point={x:s.player.x,y:s.player.y-1}){if(s.over)return;const kind=s.player.inventory[index];if(!kind)return;const rng=new Rng((s.seed^s.turn^index)>>>0);let consumed=true,spendTurn=true;if(kind==='blue-tonic'){s.player.hp=Math.min(s.player.maxHp,s.player.hp+6);push(s,'The tonic closes the worst cuts. Its sharp medicinal scent clings to you.','odd');addStatus(s,'marked',8)}else if(kind==='red-phial'){const p=throwTarget(s,target),t=at(s,p);makeNoise(s,p);if(t){const wasBarrel=t.fixture==='barrel',wasVat=t.fixture==='vat';ignite(t,5);push(s,'The red phial bursts into a low, hungry flame.','odd');if(wasBarrel)explodeBarrel(s,p);else if(wasVat)spillVat(s,p);else for(const [dx,dy] of [[0,0],...dirs] as const){const q={x:p.x+dx,y:p.y+dy},qt=at(s,q);if(qt?.kind==='acid'||qt?.kind==='oil')ignite(qt,4);const e=enemyAt(s,q.x,q.y);if(e)hurtEnemy(s,e,3)}}}else if(kind==='salt-bomb'){const p=throwTarget(s,target);makeNoise(s,p);push(s,'Salt cracks outward in a white ring.','good');for(const [dx,dy] of [[0,0],...dirs] as const){const q={x:p.x+dx,y:p.y+dy},t=at(s,q);if(t)neutralize(t);const e=enemyAt(s,q.x,q.y);if(e)hurtEnemy(s,e,e.kind==='retort-leech'?7:4)}}else if(kind==='smoke-ampoule'){const p=throwTarget(s,target);push(s,'Cold white vapor rolls low across the stones.','good');for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const t=at(s,{x:p.x+dx,y:p.y+dy});if(t&&t.kind!=='wall'&&!t.blocks){t.kind='steam';t.variant=3}}for(const e of s.enemies)e.telegraph=undefined}else if(kind==='neutralizer'){s.player.statuses=s.player.statuses.filter(st=>st.id==='warded');s.player.hp=Math.min(s.player.maxHp,s.player.hp+2);push(s,'The neutralizer tastes like wet stone. The sharp symptoms recede.','good');for(const [dx,dy] of [[0,0],...dirs] as const){const t=at(s,{x:s.player.x+dx,y:s.player.y+dy});if(t?.kind==='acid')t.kind='sludge'}}else if(kind==='copper-key'){if(!useCopperKey(s)){consumed=false;spendTurn=false}}else if(kind==='black-catalyst'){const p=throwTarget(s,target),t=at(s,p);if(t&&(t.kind==='acid'||t.kind==='fire'||t.kind==='oil'))catalystBurst(s,p);else{if(t&&t.kind!=='wall'){t.kind='sludge';t.variant=2}push(s,'The black grains sink into the floor without explanation.','odd')}}else if(kind==='chalk'){const t=at(s,s.player);if(t){t.variant=15;push(s,'You draw a clean white line across the grime. Several things dislike crossing it.','odd')}}if(consumed)s.player.inventory.splice(index,1);if(spendTurn)advance(s,rng)}
function dropFromCache(s:GameState,p:Point,t:Tile){const pool:ItemKind[]=['blue-tonic','neutralizer','smoke-ampoule','red-phial','salt-bomb','black-catalyst'];const rng=new Rng((s.seed+s.turn*97+p.x*17+p.y*31)>>>0);const kind=pool[rng.int(0,pool.length-1)]!;s.items.push({id:`cache-${s.turn}-${p.x}-${p.y}`,kind,x:p.x,y:p.y});t.fixture='rubble';t.blocks=false;t.state=2}
function openAllGates(s:GameState){let count=0;for(const t of s.tiles)if(t.fixture==='brass-gate'){t.fixture=undefined;t.blocks=false;count++}return count}
export function interactAt(s:GameState,p:Point){if(s.over||dist(s.player,p)!==1)return;const t=at(s,p);if(!t?.fixture)return;const rng=new Rng((s.seed^s.turn^p.x*131^p.y*977)>>>0);switch(t.fixture){case'boiler':{push(s,'You wrench the boiler valve open. Steam punches through the service floor.','odd');makeNoise(s,p);for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){if(Math.abs(dx)+Math.abs(dy)>2)continue;const q=at(s,{x:p.x+dx,y:p.y+dy});if(q&&q.kind!=='wall'&&!q.blocks){q.kind='steam';q.variant=3}}t.state=(t.state??0)+1;break}case'lever':{const n=openAllGates(s);t.state=1;push(s,n?'The lever drops. Somewhere east, brass teeth disengage.':'The lever is already down.','good');makeNoise(s,p);break}case'fountain':{if((t.state??0)<=0){push(s,'Only mineral crust remains in the basin.');return}s.player.hp=Math.min(s.player.maxHp,s.player.hp+4);s.player.statuses=s.player.statuses.filter(st=>st.id==='warded');t.state=0;push(s,'You rinse your hands and mouth in the bitter physic water.','good');break}case'sealed-cache':{const keyIndex=s.player.inventory.indexOf('copper-key');if(keyIndex>=0){s.player.inventory.splice(keyIndex,1);push(s,'The copper key opens the cache cleanly.','good')}else{push(s,'The cache opens with a glassy cough. Something inside has already broken.','odd');makeNoise(s,p);const q=at(s,{x:s.player.x,y:s.player.y});if(q){q.kind='glass';q.variant=2}addStatus(s,'bleeding',2)}dropFromCache(s,p,t);break}case'ward-pylon':{if((t.state??0)>0){push(s,'The pylon has gone dull.');return}for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){const q=at(s,{x:p.x+dx,y:p.y+dy});if(q?.kind==='rune')q.kind='floor'}addStatus(s,'warded',6);t.state=1;push(s,'The pylon gives one dry click. The nearby sigils fade.','odd');break}case'incinerator':{if((t.state??0)>0){push(s,'The furnace mouth is already hot.');return}t.state=1;makeNoise(s,p);push(s,'The pilot catches. Heat runs down the glassworks wall.','odd');for(const [dx,dy] of dirs){const q=at(s,{x:p.x+dx,y:p.y+dy});if(q)ignite(q,4)}break}case'retort':{if((t.state??0)>0){push(s,'The retort is empty.');return}t.state=1;s.items.push({id:`retort-${s.turn}`,kind:'neutralizer',x:p.x,y:p.y});t.blocks=false;t.fixture='table';push(s,'A thumb of clear neutralizer remains in the condenser.','good');break}case'brass-gate':{const keyIndex=s.player.inventory.indexOf('copper-key');if(keyIndex<0){push(s,'The brass gate has no handle on this side.');return}s.player.inventory.splice(keyIndex,1);t.fixture=undefined;t.blocks=false;push(s,'The copper key releases the gate.','good');break}default:{push(s,`You check the ${t.fixture}. Nothing immediate gives way.`);return}}advance(s,rng)}
export function wait(s:GameState){if(s.over)return;s.player.guard=2;push(s,'You listen and brace.');advance(s,new Rng((s.seed+s.turn)>>>0))}
export function inspectAt(s:GameState,p:Point):string{const e=enemyAt(s,p.x,p.y);if(e)return`${ENEMIES[e.kind].name} — ${ENEMIES[e.kind].note}`;const t=at(s,p);if(!t)return'';if(t.fixture){const usable=['boiler','lever','fountain','sealed-cache','ward-pylon','incinerator','retort','brass-gate'].includes(t.fixture);return`${t.room??'stone'} / ${t.fixture}${t.blocks?' · blocks movement':''}${usable?' · tap adjacent to interact':''}`}const terrain:Partial<Record<Tile['kind'],string>>={acid:'corrosive',steam:'scalding + blocks sight',sludge:'slows movement',glass:'cuts exposed feet',oil:'highly flammable',rune:'unknown ward'};return`${t.room??'stone'} / ${t.kind}${terrain[t.kind]?` · ${terrain[t.kind]}`:''}`}
