import { drawMap as baseDrawMap, screenToTile } from './render4';
import type { GameState } from '../game/types';

const TS=32;
function occupied(s:GameState,x:number,y:number){return s.player.x===x&&s.player.y===y||s.enemies.some(e=>e.x===x&&e.y===y)||s.items.some(i=>i.x===x&&i.y===y)}
function wash(room=''){if(room.includes('herbal')||room.includes('spice')||room.includes('courtyard'))return'#202319';if(room.includes('glass')||room.includes('assay')||room.includes('crystal')||room.includes('mirror')||room.includes('master'))return'#18211f';if(room.includes('distill')||room.includes('furnace')||room.includes('kiln')||room.includes('alembic')||room.includes('reaction'))return'#242019';if(room.includes('cistern')||room.includes('cooling')||room.includes('drain')||room.includes('condenser'))return'#172224';if(room.includes('sealed')||room.includes('black-market')||room.includes('sanctum')||room.includes('crypt')||room.includes('ossuary'))return'#201a1d';if(room.includes('under')||room.includes('passage')||room.includes('ash'))return'#1b1e19';return'#1d2019'}
function macro(x:number,y:number,v=0){let n=Math.imul(x*17+y*41+v*113,0x27d4eb2d);n=(n^(n>>>15))>>>0;return n/4294967296}
export function drawMap(canvas:HTMLCanvasElement,s:GameState){baseDrawMap(canvas,s);const c=canvas.getContext('2d')!;for(let y=0;y<s.height;y++)for(let x=0;x<s.width;x++){const t=s.tiles[y*s.width+x];if(!t?.visible||t.kind!=='floor'||t.fixture||occupied(s,x,y))continue;const X=x*TS,Y=y*TS,r=macro(Math.floor(x/2),Math.floor(y/2),t.variant);c.globalAlpha=.54;c.fillStyle=wash(t.room);c.fillRect(X+1,Y+1,30,30);c.globalAlpha=1;if(x%2===0){c.globalAlpha=.09;c.fillStyle='#a18e68';c.fillRect(X+1,Y+3,1,27);c.globalAlpha=1}if(y%2===0){c.globalAlpha=.09;c.fillStyle='#a18e68';c.fillRect(X+3,Y+1,27,1);c.globalAlpha=1}if(r>.84){c.globalAlpha=.22;c.fillStyle='#0c0f0b';c.fillRect(X+8,Y+20,14,4);c.globalAlpha=.12;c.fillStyle='#9b7751';c.fillRect(X+10,Y+20,8,1);c.globalAlpha=1}else if(r<.10){c.globalAlpha=.16;c.fillStyle='#34352a';c.fillRect(X+7,Y+8,18,5);c.globalAlpha=.10;c.fillStyle='#b1a080';c.fillRect(X+9,Y+9,12,1);c.globalAlpha=1}}}
export { screenToTile };
