import type { FloorMap, GameState, ThemePalette } from '../core/types';
import { itemById } from '../content/items';
import { monsterById } from '../content/monsters';
import { resolveThemeContext, themeById } from '../world/themes';
function blendHex(a:string,b:string,t:number):string{const parse=(hex:string)=>[1,3,5].map((offset)=>Number.parseInt(hex.slice(offset,offset+2),16));const aa=parse(a),bb=parse(b),out=aa.map((value,index)=>Math.round(value+(bb[index]!-value)*t));return `#${out.map((value)=>value.toString(16).padStart(2,'0')).join('')}`;}
function paletteForState(state:GameState):ThemePalette{const context=resolveThemeContext(state.coord);if(!context.blend)return context.primary.palette;const t=context.blend.weight;return{wall:blendHex(context.primary.palette.wall,context.blend.target.palette.wall,t),floor:blendHex(context.primary.palette.floor,context.blend.target.palette.floor,t),accent:blendHex(context.primary.palette.accent,context.blend.target.palette.accent,t),danger:blendHex(context.primary.palette.danger,context.blend.target.palette.danger,t),water:blendHex(context.primary.palette.water,context.blend.target.palette.water,t)};}
function tileGlyph(map:FloorMap,x:number,y:number):string{return map.exits.find((entry)=>entry.x===x&&entry.y===y)?.glyph??map.tiles[y*map.width+x]!.glyph;}
export function renderCanvas(canvas:HTMLCanvasElement,state:GameState):void{const ctx=canvas.getContext('2d');if(!ctx)return;const palette=paletteForState(state),containerWidth=Math.max(320,canvas.clientWidth),containerHeight=Math.max(260,canvas.clientHeight),cellW=Math.floor(containerWidth/state.floor.width),cellH=Math.floor(containerHeight/state.floor.height),cell=Math.max(7,Math.min(cellW,cellH));canvas.width=state.floor.width*cell;canvas.height=state.floor.height*cell;ctx.fillStyle='#07090d';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.font=`${Math.max(8,Math.floor(cell*.95))}px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace`;ctx.textAlign='center';ctx.textBaseline='middle';const exitByPos=new Map(state.floor.exits.map((exit)=>[`${exit.x},${exit.y}`,exit])),visible=new Set(state.visible),explored=new Set(state.explored);for(let y=0;y<state.floor.height;y+=1)for(let x=0;x<state.floor.width;x+=1){const key=`${x},${y}`;if(!explored.has(key))continue;const tile=state.floor.tiles[y*state.floor.width+x]!,glyph=tileGlyph(state.floor,x,y),exit=exitByPos.get(key);let color=exit?palette.accent:tile.kind==='wall'?palette.wall:tile.kind==='water'?palette.water:tile.kind==='lava'?palette.danger:tile.kind==='rubble'?blendHex(palette.wall,palette.floor,.55):palette.floor;if(!visible.has(key))color=blendHex(color,'#07090d',.64);ctx.fillStyle=color;ctx.fillText(glyph,x*cell+cell/2,y*cell+cell/2);}for(const entry of state.items){if(!visible.has(`${entry.x},${entry.y}`))continue;const def=itemById(entry.defId);ctx.fillStyle=def.color;ctx.fillText(def.glyph,entry.x*cell+cell/2,entry.y*cell+cell/2);}for(const monster of state.monsters){if(!visible.has(`${monster.x},${monster.y}`))continue;const def=monsterById(monster.defId);ctx.fillStyle=def.color;ctx.fillText(def.glyph,monster.x*cell+cell/2,monster.y*cell+cell/2);}ctx.fillStyle='#f4f4f1';ctx.fillText('@',state.player.x*cell+cell/2,state.player.y*cell+cell/2);}
export function describeState(state:GameState):string{const theme=themeById(state.themeId);return `${theme.name} · ${state.coord.depth}F`;}
