import type { ItemDefinition } from '../core/types';

const item = (
  id: string,
  name: string,
  glyph: string,
  color: string,
  category: ItemDefinition['category'],
  rarity: number,
  tags: string[],
  effects: ItemDefinition['effects'],
): ItemDefinition => ({ id, name, glyph, color, category, rarity, tags, effects });

export const EXTRA_ITEMS: ItemDefinition[] = [
  item('hook-spear','Hook Spear',')','#b9a57f','weapon',1,['polearm','control'],[{op:'damage',amount:3},{op:'push',distance:1}]),
  item('serrated-cleaver','Serrated Cleaver',')','#c49b7f','weapon',2,['blade','bleed'],[{op:'damage',amount:5},{op:'status',id:'bleeding',duration:3}]),
  item('storm-pike','Storm Pike',')','#b7c8ed','weapon',3,['polearm','shock'],[{op:'damage',amount:6,damageType:'shock'},{op:'status',id:'dazed',duration:1}]),
  item('grave-mace','Grave Mace',')','#b9afa0','weapon',3,['blunt','undead'],[{op:'damage',amount:7},{op:'status',id:'armor-break',duration:3}]),
  item('fen-lance','Fen Lance',')','#93ad68','weapon',3,['polearm','venom'],[{op:'damage',amount:6},{op:'status',id:'poisoned',duration:4}]),
  item('mirror-sabre','Mirror Sabre',')','#c3d0e8','weapon',4,['blade','crystal'],[{op:'damage',amount:8},{op:'status',id:'focused',duration:2}]),
  item('cinder-axe','Cinder Axe',')','#db8e63','weapon',4,['blade','fire'],[{op:'damage',amount:9,damageType:'fire'},{op:'status',id:'burning',duration:2}]),
  item('void-pike','Void Pike',')','#b38bd2','weapon',5,['polearm','void'],[{op:'damage',amount:10,damageType:'void'},{op:'push',distance:2}]),
  item('execution-chain','Execution Chain',')','#a9a4a0','weapon',5,['blunt','control'],[{op:'damage',amount:9},{op:'status',id:'pinned',duration:1}]),
  item('star-needle','Star Needle',')','#efd07f','weapon',5,['blade','star'],[{op:'damage',amount:11},{op:'status',id:'marked',duration:4}]),

  item('reed-cloak','Reed Cloak','[','#88a37a','armor',1,['light','aquatic'],[{op:'status',id:'armor',duration:999,magnitude:1},{op:'status',id:'water-step',duration:999}]),
  item('barbed-hide','Barbed Hide','[','#9c806f','armor',2,['medium','beast'],[{op:'status',id:'armor',duration:999,magnitude:3}]),
  item('storm-weave','Storm Weave','[','#9faed3','armor',3,['light','resist:shock'],[{op:'status',id:'armor',duration:999,magnitude:2}]),
  item('cinder-scale','Cinder Scale','[','#b98a70','armor',3,['medium','resist:fire'],[{op:'status',id:'armor',duration:999,magnitude:3},{op:'status',id:'fire-ward',duration:999}]),
  item('mirror-mail','Mirror Mail','[','#aebdd9','armor',4,['medium','crystal','resist:shock'],[{op:'status',id:'armor',duration:999,magnitude:4}]),
  item('void-silk','Void Silk','[','#a08bbd','armor',4,['light','resist:void'],[{op:'status',id:'armor',duration:999,magnitude:2},{op:'status',id:'lucid',duration:999}]),
  item('glacier-plate','Glacier Plate','[','#b9d8e4','armor',5,['heavy','ice','resist:cold'],[{op:'status',id:'armor',duration:999,magnitude:6},{op:'status',id:'cold-ward',duration:999}]),
  item('forge-bastion','Forge Bastion','[','#c09b6b','armor',5,['heavy','fire','resist:fire'],[{op:'status',id:'armor',duration:999,magnitude:7},{op:'status',id:'fire-ward',duration:999}]),

  item('murky-restorative','Murky Restorative','!','#9aa59c','consumable',1,['potion','mystery'],[{op:'heal',amount:8}]),
  item('bitter-restorative','Bitter Restorative','!','#b09a72','consumable',2,['potion','mystery'],[{op:'heal',amount:16}]),
  item('smoking-vial','Smoking Vial','!','#d2825e','consumable',2,['potion','mystery','fire'],[{op:'spawn-terrain',tile:'lava',radius:1,duration:5}]),
  item('silver-vial','Silver Vial','!','#c6d0d2','consumable',2,['potion','mystery'],[{op:'status',id:'hasted',duration:5}]),
  item('black-vial','Black Vial','!','#89828f','consumable',3,['potion','mystery','void'],[{op:'teleport',radius:10}]),
  item('violet-vial','Violet Vial','!','#b49acb','consumable',3,['potion','mystery'],[{op:'status',id:'focused',duration:8,magnitude:2}]),
  item('caustic-vial','Caustic Vial','!','#a8bf66','consumable',3,['potion','mystery','acid'],[{op:'status',id:'armor-break',duration:6,magnitude:3}]),
  item('blood-vial','Blood Vial','!','#c86b75','consumable',4,['potion','mystery'],[{op:'status',id:'berserk',duration:6,magnitude:1}]),
  item('white-vial','White Vial','!','#dce5e8','consumable',4,['potion','mystery','cold'],[{op:'status',id:'chilled',duration:5,magnitude:3}]),
  item('gold-vial','Gold Vial','!','#dbc278','consumable',5,['potion','mystery'],[{op:'heal',amount:30},{op:'status',id:'focused',duration:5}]),
  item('smoke-ampoule','Smoke Ampoule','!','#888b8f','consumable',2,['potion','mystery','escape'],[{op:'teleport',radius:5}]),
  item('ward-ampoule','Ward Ampoule','!','#8fb7c3','consumable',3,['potion','mystery'],[{op:'status',id:'guarding',duration:4,magnitude:1}]),

  item('etched-map','Etched Map','?','#d1c6aa','tool',1,['scroll','mystery','mapping'],[{op:'reveal',radius:16}]),
  item('red-glyph-strip','Red Glyph Strip','?','#cf7a6e','tool',2,['scroll','mystery','fire'],[{op:'damage',amount:9,damageType:'fire'}]),
  item('blue-glyph-strip','Blue Glyph Strip','?','#8eb7cf','tool',2,['scroll','mystery','shock'],[{op:'damage',amount:8,damageType:'shock'}]),
  item('green-glyph-strip','Green Glyph Strip','?','#98b46a','tool',2,['scroll','mystery'],[{op:'status',id:'poisoned',duration:5,magnitude:2}]),
  item('ashen-glyph-strip','Ashen Glyph Strip','?','#a99c91','tool',3,['scroll','mystery'],[{op:'spawn-terrain',tile:'rubble',radius:2,duration:8}]),
  item('mirror-glyph-strip','Mirror Glyph Strip','?','#bac9dc','tool',3,['scroll','mystery'],[{op:'status',id:'focused',duration:8}]),
  item('void-glyph-strip','Void Glyph Strip','?','#aa8ac3','tool',4,['scroll','mystery','void'],[{op:'teleport',radius:12}]),
  item('binding-glyph-strip','Binding Glyph Strip','?','#b7a98f','tool',4,['scroll','mystery','control'],[{op:'status',id:'pinned',duration:2}]),
  item('signal-flare','Signal Flare','?','#e39b62','tool',2,['light','fire'],[{op:'reveal',radius:18}]),
  item('phase-hook','Phase Hook','?','#ad9ccd','tool',4,['mobility','void'],[{op:'teleport',radius:6}]),
  item('ward-stone','Ward Stone','?','#a6b9bf','tool',3,['defense'],[{op:'status',id:'guarding',duration:3}]),
  item('war-drum','War Drum','?','#ba916f','tool',4,['noise','combat'],[{op:'status',id:'berserk',duration:5}]),
  item('cold-mirror','Cold Mirror','?','#b9d9e5','tool',4,['ice','control'],[{op:'status',id:'chilled',duration:4,magnitude:2}]),
  item('spore-jar','Spore Jar','?','#bbb66d','tool',3,['fungal','control'],[{op:'status',id:'confused',duration:3}]),
  item('grave-whistle','Grave Whistle','?','#c4b9a2','tool',4,['undead','summon'],[{op:'summon',tag:'undead',count:2}]),
  item('prism-lure','Prism Lure','?','#bdc7eb','tool',5,['crystal','summon'],[{op:'summon',tag:'crystal',count:1}]),

  item('ring-of-pressure','Ring of Pressure','"','#c4a875','relic',4,['control'],[{op:'status',id:'focused',duration:999}]),
  item('mirror-eye','Mirror Eye','"','#c6d0eb','relic',4,['crystal'],[{op:'reveal',radius:20}]),
  item('fen-heart','Fen Heart','"','#9bb56b','relic',4,['venom','resist:poison'],[{op:'status',id:'poison-ward',duration:999}]),
  item('ember-lung','Ember Lung','"','#d98b61','relic',4,['fire','resist:fire'],[{op:'status',id:'fire-ward',duration:999}]),
  item('storm-knot','Storm Knot','"','#aebee4','relic',5,['shock','resist:shock'],[{op:'status',id:'focused',duration:999}]),
  item('frozen-second','Frozen Second','"','#c5e1ea','relic',5,['ice','resist:cold'],[{op:'status',id:'cold-ward',duration:999}]),
  item('void-anchor','Void Anchor','"','#ad91c7','relic',5,['void','resist:void'],[{op:'status',id:'lucid',duration:999}]),
  item('crown-of-thorns','Crown of Thorns','"','#d0aa82','relic',5,['royal','combat'],[{op:'status',id:'berserk',duration:999}]),
];
