import type { ItemDefinition } from '../core/types';

const i=(id:string,name:string,glyph:string,color:string,category:ItemDefinition['category'],rarity:number,tags:string[],effects:ItemDefinition['effects']):ItemDefinition=>({id,name,glyph,color,category,rarity,tags,effects});

export const FOUNDATION_ITEMS:ItemDefinition[]=[
  i('hard-biscuit','Hard Biscuit','%','#c9aa7c','consumable',1,['food','ration'],[{op:'nutrition',amount:360}]),
  i('salt-meat','Salt Meat','%','#bd806d','consumable',1,['food','ration','meat'],[{op:'nutrition',amount:520}]),
  i('moss-cake','Moss Cake','%','#91a86c','consumable',1,['food','plant'],[{op:'nutrition',amount:300}]),
  i('pickled-eel','Pickled Eel','%','#76a7ad','consumable',1,['food','aquatic'],[{op:'nutrition',amount:460}]),
  i('ember-root','Ember Root','%','#c57d4e','consumable',1,['food','fire','plant'],[{op:'nutrition',amount:340}]),
  i('spore-loaf','Spore Loaf','%','#aaa45f','consumable',1,['food','fungal'],[{op:'nutrition',amount:430}]),
  i('bone-broth','Bone Broth','%','#c7b899','consumable',1,['food','broth'],[{op:'nutrition',amount:390},{op:'heal',amount:3}]),
  i('miner-stew','Miner Stew','%','#b28b66','consumable',2,['food','ration'],[{op:'nutrition',amount:650},{op:'heal',amount:4}]),
  i('crystal-pear','Crystal Pear','%','#a9c4df','consumable',2,['food','crystal','plant'],[{op:'nutrition',amount:350},{op:'status',id:'focused',duration:5}]),
  i('fen-rice','Fen Rice','%','#a8b96a','consumable',2,['food','venom','plant'],[{op:'nutrition',amount:480},{op:'status',id:'antivenom',duration:8}]),
  i('archive-ration','Archive Ration','%','#b3a88d','consumable',2,['food','ration'],[{op:'nutrition',amount:560}]),
  i('ash-flatbread','Ash Flatbread','%','#bca08b','consumable',2,['food','fire'],[{op:'nutrition',amount:500},{op:'status',id:'fire-ward',duration:5}]),
  i('red-marrow','Red Marrow','%','#c77b82','consumable',2,['food','flesh'],[{op:'nutrition',amount:520},{op:'heal',amount:5}]),
  i('gear-cheese','Gearhouse Cheese','%','#d0b36f','consumable',2,['food','ration'],[{op:'nutrition',amount:620}]),
  i('rime-berries','Rime Berries','%','#b8d8e1','consumable',2,['food','ice','plant'],[{op:'nutrition',amount:330},{op:'status',id:'cold-ward',duration:6}]),
  i('palace-kelp','Palace Kelp','%','#7fb2a3','consumable',2,['food','aquatic','plant'],[{op:'nutrition',amount:420}]),
  i('night-fruit','Night Fruit','%','#9d83b8','consumable',3,['food','void','plant'],[{op:'nutrition',amount:410},{op:'status',id:'lucid',duration:6}]),
  i('royal-pie','Royal Hand Pie','%','#d1ad78','consumable',3,['food','royal'],[{op:'nutrition',amount:740},{op:'heal',amount:5}]),
  i('dream-plum','Dream Plum','%','#b895cb','consumable',3,['food','dream','plant'],[{op:'nutrition',amount:390},{op:'status',id:'focused',duration:8}]),
  i('forge-jerky','Forge Jerky','%','#d7935d','consumable',3,['food','fire','meat'],[{op:'nutrition',amount:680},{op:'status',id:'fire-ward',duration:4}]),
  i('traveler-ration','Traveler Ration','%','#c5ad86','consumable',2,['food','ration'],[{op:'nutrition',amount:800}]),
  i('field-pemmican','Field Pemmican','%','#a97761','consumable',3,['food','ration','meat'],[{op:'nutrition',amount:980}]),
  i('honeyed-nuts','Honeyed Nuts','%','#d0aa61','consumable',2,['food','plant'],[{op:'nutrition',amount:450},{op:'heal',amount:2}]),
  i('bitter-mushroom','Bitter Mushroom','%','#9c9a63','consumable',1,['food','fungal'],[{op:'nutrition',amount:260}]),
  i('clean-water-flask','Clean Water Flask','%','#83b8c2','consumable',1,['food','water'],[{op:'nutrition',amount:180},{op:'status',id:'cleansed',duration:1}]),
  i('temple-offering-cake','Offering Cake','%','#d5c99f','consumable',3,['food','holy'],[{op:'nutrition',amount:600},{op:'status',id:'guarding',duration:4}]),
  i('black-sausage','Black Sausage','%','#7f706d','consumable',3,['food','meat','void'],[{op:'nutrition',amount:720},{op:'status',id:'lucid',duration:4}]),
  i('star-sugar','Star Sugar','%','#e6c775','consumable',4,['food','star'],[{op:'nutrition',amount:500},{op:'status',id:'hasted',duration:3}]),
  i('pilgrim-feast','Pilgrim Feast','%','#d1b286','consumable',4,['food','ration'],[{op:'nutrition',amount:1300},{op:'heal',amount:8}]),
  i('void-truffle','Void Truffle','%','#aa8bc3','consumable',4,['food','void','fungal'],[{op:'nutrition',amount:620},{op:'teleport',radius:4}]),

  i('sling','Hunter Sling',')','#b79a75','weapon',1,['ranged','range:6','projectile'],[{op:'damage',amount:3}]),
  i('short-bow','Short Bow',')','#c4a070','weapon',1,['ranged','range:7','projectile'],[{op:'damage',amount:4}]),
  i('iron-crossbow','Iron Crossbow',')','#92999d','weapon',2,['ranged','range:8','projectile'],[{op:'damage',amount:6}]),
  i('fen-blowpipe','Fen Blowpipe',')','#8da760','weapon',2,['ranged','range:7','venom'],[{op:'damage',amount:3},{op:'status',id:'poisoned',duration:3}]),
  i('spore-darter','Spore Darter',')','#b2ad67','weapon',2,['ranged','range:6','fungal'],[{op:'damage',amount:4},{op:'status',id:'confused',duration:1}]),
  i('storm-arbalest','Storm Arbalest',')','#9eb4dd','weapon',3,['ranged','range:8','shock'],[{op:'damage',amount:7,damageType:'shock'}]),
  i('prism-bow','Prism Bow',')','#b5c8ec','weapon',3,['ranged','range:9','crystal'],[{op:'damage',amount:7}]),
  i('ash-repeater','Ash Repeater',')','#c58a66','weapon',3,['ranged','range:7','fire'],[{op:'damage',amount:7,damageType:'fire'}]),
  i('bone-longbow','Bone Longbow',')','#c9bca0','weapon',3,['ranged','range:9','bone'],[{op:'damage',amount:8}]),
  i('rime-crossbow','Rime Crossbow',')','#b8d9e5','weapon',4,['ranged','range:8','ice'],[{op:'damage',amount:8,damageType:'cold'},{op:'status',id:'chilled',duration:2}]),
  i('tide-harpooner','Tide Harpooner',')','#7fb5b0','weapon',4,['ranged','range:7','aquatic'],[{op:'damage',amount:9},{op:'push',distance:1}]),
  i('royal-windlass','Royal Windlass',')','#c9a56f','weapon',4,['ranged','range:9','royal'],[{op:'damage',amount:10}]),
  i('dream-bow','Dream Bow',')','#b698d0','weapon',5,['ranged','range:10','dream'],[{op:'damage',amount:10},{op:'status',id:'confused',duration:1}]),
  i('void-launcher','Void Launcher',')','#a286be','weapon',5,['ranged','range:9','void'],[{op:'damage',amount:11,damageType:'void'}]),
  i('star-ballistette','Star Ballistette',')','#e8bd65','weapon',5,['ranged','range:10','star','fire'],[{op:'damage',amount:12,damageType:'fire'}]),

  i('stone-pouch','Stone Pouch',';','#9f9485','consumable',1,['ammo','projectile'],[{op:'ammo',amount:5}]),
  i('arrow-bundle','Arrow Bundle',';','#bd9c72','consumable',1,['ammo','projectile'],[{op:'ammo',amount:8}]),
  i('bolt-case','Bolt Case',';','#9ba0a2','consumable',2,['ammo','projectile'],[{op:'ammo',amount:10}]),
  i('bone-arrows','Bone Arrows',';','#c8b99c','consumable',2,['ammo','bone'],[{op:'ammo',amount:9}]),
  i('fen-darts','Fen Darts',';','#8da660','consumable',2,['ammo','venom'],[{op:'ammo',amount:7}]),
  i('prism-shafts','Prism Shafts',';','#adc3e7','consumable',3,['ammo','crystal'],[{op:'ammo',amount:10}]),
  i('storm-bolts','Storm Bolts',';','#a6b8df','consumable',3,['ammo','shock'],[{op:'ammo',amount:11}]),
  i('cinder-arrows','Cinder Arrows',';','#cf8b60','consumable',3,['ammo','fire'],[{op:'ammo',amount:11}]),
  i('rime-bolts','Rime Bolts',';','#bbdce7','consumable',3,['ammo','ice'],[{op:'ammo',amount:11}]),
  i('royal-quiver','Royal Quiver',';','#cfad75','consumable',4,['ammo','royal'],[{op:'ammo',amount:14}]),
  i('void-needles','Void Needles',';','#a88ac0','consumable',4,['ammo','void'],[{op:'ammo',amount:13}]),
  i('star-shafts','Star Shafts',';','#e5bf69','consumable',5,['ammo','star'],[{op:'ammo',amount:16}]),

  i('field-bandage','Field Bandage','!','#d4c5ad','consumable',1,['medicine'],[{op:'heal',amount:6}]),
  i('surveyor-map','Surveyor Map','?','#d5c7aa','tool',2,['mapping'],[{op:'reveal',radius:20}]),
  i('smoke-pot','Smoke Pot','!','#85898d','consumable',2,['escape'],[{op:'teleport',radius:5}]),
  i('ward-salve','Ward Salve','!','#9fbdc1','consumable',2,['defense'],[{op:'status',id:'guarding',duration:5}]),
  i('focus-incense','Focus Incense','!','#c3ad8a','consumable',2,['focus'],[{op:'status',id:'focused',duration:10}]),
  i('miners-tonic','Miners Tonic','!','#b99368','consumable',2,['medicine'],[{op:'heal',amount:8},{op:'nutrition',amount:180}]),
  i('route-flare','Route Flare','?','#d69a63','tool',2,['mapping','light'],[{op:'reveal',radius:22}]),
  i('escape-chalk','Escape Chalk','?','#d7d0c3','tool',3,['escape','mapping'],[{op:'reveal',radius:12},{op:'teleport',radius:4}]),
  i('shock-grounder','Shock Grounder','?','#a4b6c8','tool',3,['shock','defense'],[{op:'status',id:'focused',duration:6}]),
  i('cold-pack','Cold Pack','!','#b9d6df','consumable',2,['ice','medicine'],[{op:'status',id:'cold-ward',duration:8},{op:'heal',amount:3}]),
  i('fire-blanket','Fire Blanket','!','#c89578','consumable',2,['fire','defense'],[{op:'status',id:'fire-ward',duration:8}]),
  i('antitoxin-kit','Antitoxin Kit','!','#a6ba70','consumable',2,['venom','medicine'],[{op:'status',id:'antivenom',duration:18}]),
  i('waystone','Waystone','?','#9ea4b1','tool',3,['navigation'],[{op:'reveal',radius:24}]),
  i('echo-bell','Echo Bell','?','#c5b794','tool',3,['sound','mapping'],[{op:'reveal',radius:16}]),
  i('emergency-ration','Emergency Ration','%','#cfaa78','consumable',3,['food','ration','medicine'],[{op:'nutrition',amount:700},{op:'heal',amount:4}]),
  i('hunter-kit','Hunter Kit','?','#ad936d','tool',3,['ammo','survival'],[{op:'ammo',amount:6},{op:'reveal',radius:7}]),
  i('deep-delver-kit','Deep Delver Kit','?','#b1a68f','tool',4,['survival','mapping'],[{op:'ammo',amount:10},{op:'reveal',radius:18}]),
  i('pilgrim-kit','Pilgrim Kit','?','#cdbb94','tool',4,['survival','holy'],[{op:'nutrition',amount:420},{op:'status',id:'guarding',duration:4}]),
];
