import type { MonsterDefinition } from '../core/types';

const m=(theme:string,id:string,name:string,glyph:string,color:string,hp:number,attack:number,defense:number,ai:MonsterDefinition['ai'],minDepth:number,tags:string[],abilities:MonsterDefinition['abilities']=[]):MonsterDefinition=>({id:`${theme}-${id}`,name,glyph,color,maxHp:hp,attack,defense,ai,minDepth,tags:[...tags,`theme:${theme}`],abilities});

export const FOUNDATION_MONSTERS:MonsterDefinition[]=[
  m('moss-cistern','pipe-skulker','Pipe Skulker','k','#80946f',13,5,1,'stalker',1,['humanoid'],[{op:'status',id:'bleeding',duration:2}]),
  m('moss-cistern','moss-shell','Moss Shell','s','#72876b',24,5,5,'guard',1,['beast','resist:poison']),
  m('moss-cistern','drain-witch','Drain Witch','w','#9fa985',17,6,2,'caster',1,['humanoid','caster'],[{op:'status',id:'slowed',duration:2}]),
  m('drowned-aqueduct','lock-runner','Lock Runner','r','#6f9ba4',15,6,1,'skirmisher',1,['aquatic','humanoid']),
  m('drowned-aqueduct','sluice-serpent','Sluice Serpent','S','#5f919d',23,7,2,'stalker',1,['aquatic','beast'],[{op:'push',distance:1}]),
  m('drowned-aqueduct','tide-hexer','Tide Hexer','x','#8bb2bd',19,6,2,'caster',1,['aquatic','caster'],[{op:'status',id:'pinned',duration:1}]),
  m('ember-mine','lamp-raider','Lamp Raider','r','#bd8057',17,7,2,'stalker',1,['humanoid','fire']),
  m('ember-mine','ore-mole','Ore Mole','m','#97765f',26,7,4,'brute',1,['beast']),
  m('ember-mine','slag-caller','Slag Caller','c','#d48d5d',20,7,2,'caster',1,['humanoid','caster','fire'],[{op:'summon',tag:'construct',count:1}]),

  m('fungal-vault','cap-stalker','Cap Stalker','c','#9ca15e',22,8,2,'stalker',21,['fungal','resist:poison']),
  m('fungal-vault','spore-bomber','Spore Bomber','b','#c0b86e',18,8,1,'skirmisher',21,['fungal'],[{op:'status',id:'confused',duration:2}]),
  m('fungal-vault','root-colossus','Root Colossus','R','#7f8b61',36,9,6,'brute',21,['fungal','plant','vuln:fire']),
  m('ossuary-terraces','bone-taxer','Bone Taxer','t','#b5aa93',24,8,3,'guard',21,['undead','humanoid']),
  m('ossuary-terraces','mourning-lamp','Mourning Lamp','l','#d1c7b1',17,9,1,'caster',21,['spirit'],[{op:'status',id:'blinded',duration:2}]),
  m('ossuary-terraces','grave-horse','Grave Horse','H','#9d927e',33,10,4,'brute',21,['undead','beast'],[{op:'push',distance:2}]),
  m('ironwarren','bolt-thief','Bolt Thief','t','#9b866a',20,9,2,'skirmisher',21,['humanoid']),
  m('ironwarren','riveted-ram','Riveted Ram','R','#8d9295',34,10,6,'brute',21,['construct','vuln:shock'],[{op:'push',distance:2}]),
  m('ironwarren','coil-priest','Coil Priest','p','#b4a273',23,9,3,'caster',21,['construct','caster','shock'],[{op:'damage',amount:5,damageType:'shock'}]),

  m('crystal-hollows','glass-mantis','Glass Mantis','m','#a7bce5',24,10,2,'skirmisher',41,['crystal','vermin']),
  m('crystal-hollows','mirror-hound','Mirror Hound','h','#b8c9e8',31,11,3,'stalker',41,['crystal','beast'],[{op:'teleport',radius:3}]),
  m('crystal-hollows','choir-prism','Choir Prism','P','#c1b9e6',28,10,5,'caster',41,['crystal','construct'],[{op:'damage',amount:6,damageType:'shock'}]),
  m('venom-fen','reed-assassin','Reed Assassin','a','#879b5a',26,11,2,'stalker',41,['humanoid','venom','resist:poison'],[{op:'status',id:'poisoned',duration:4}]),
  m('venom-fen','bog-bison','Bog Bison','B','#788b5d',39,11,5,'brute',41,['beast','venom'],[{op:'push',distance:2}]),
  m('venom-fen','swamp-idol','Swamp Idol','I','#a0ad6c',32,10,7,'guard',41,['construct','venom','resist:poison']),
  m('storm-archive','static-monk','Static Monk','m','#9da8ca',26,11,3,'skirmisher',41,['humanoid','shock','resist:shock']),
  m('storm-archive','living-index','Living Index','i','#b7bfdc',25,11,3,'caster',41,['caster','spirit'],[{op:'status',id:'dazed',duration:2}]),
  m('storm-archive','vault-coil','Vault Coil','C','#8795b8',40,12,7,'guard',41,['construct','shock','resist:shock','vuln:fire']),

  m('ash-cathedral','censer-knight','Censer Knight','K','#a88b7a',34,12,5,'guard',61,['humanoid','fire','resist:fire']),
  m('ash-cathedral','smoke-angel','Smoke Angel','A','#c39b85',29,12,3,'caster',61,['spirit','fire'],[{op:'status',id:'blinded',duration:3}]),
  m('ash-cathedral','ash-lion','Ash Lion','L','#b2765e',41,13,4,'stalker',61,['beast','fire','resist:fire']),
  m('flesh-cloister','artery-hunter','Artery Hunter','h','#bd747d',30,13,3,'stalker',61,['flesh','aberrant'],[{op:'status',id:'bleeding',duration:4}]),
  m('flesh-cloister','skin-banner','Skin Banner','B','#d19299',33,11,6,'guard',61,['flesh','humanoid']),
  m('flesh-cloister','pulse-singer','Pulse Singer','s','#d88390',28,12,2,'caster',61,['flesh','caster'],[{op:'status',id:'slowed',duration:3}]),
  m('clockwork-necropolis','minute-hand','Minute Hand','h','#a78f65',31,13,4,'skirmisher',61,['construct','vuln:shock']),
  m('clockwork-necropolis','brass-mourner','Brass Mourner','M','#b89f72',40,12,7,'guard',61,['construct','undead']),
  m('clockwork-necropolis','clock-priest','Clock Priest','p','#c3a875',30,13,3,'caster',61,['construct','caster'],[{op:'status',id:'slowed',duration:3}]),

  m('frozen-observatory','rime-panther','Rime Panther','p','#a9cedd',34,14,3,'stalker',81,['ice','beast','resist:cold','vuln:fire']),
  m('frozen-observatory','snow-oracle','Snow Oracle','o','#d2e6ec',31,13,3,'caster',81,['ice','caster','resist:cold'],[{op:'status',id:'chilled',duration:4}]),
  m('frozen-observatory','ice-bulwark','Ice Bulwark','B','#98b7c5',47,13,8,'guard',81,['ice','construct','resist:cold','vuln:fire']),
  m('sunken-palace','pearl-lancer','Pearl Lancer','L','#89b4b0',38,14,4,'skirmisher',81,['aquatic','humanoid']),
  m('sunken-palace','drowned-seer','Drowned Seer','s','#92b8ba',34,14,3,'caster',81,['aquatic','undead','caster'],[{op:'damage',amount:8,damageType:'cold'}]),
  m('sunken-palace','coral-turtle','Coral Turtle','T','#779b91',51,13,9,'guard',81,['aquatic','beast']),
  m('void-garden','night-hare','Night Hare','r','#9885b4',28,14,2,'skirmisher',81,['void','beast','resist:void']),
  m('void-garden','hollow-rose','Hollow Rose','R','#b483bd',35,13,5,'guard',81,['void','plant','resist:void','vuln:fire']),
  m('void-garden','starless-druid','Starless Druid','d','#a98ac4',33,14,3,'caster',81,['void','caster','plant'],[{op:'summon',tag:'plant',count:2}]),

  m('royal-chasm','banner-duelist','Banner Duelist','D','#b99570',45,16,5,'skirmisher',101,['humanoid','royal']),
  m('royal-chasm','crown-bear','Crown Bear','B','#a78564',58,17,6,'brute',101,['beast','royal'],[{op:'push',distance:3}]),
  m('royal-chasm','oath-seer','Oath Seer','s','#c5a27d',41,15,4,'caster',101,['humanoid','caster','royal'],[{op:'status',id:'armor-break',duration:4,magnitude:2}]),
  m('dream-prison','corridor-mime','Corridor Mime','m','#9f8ab9',39,15,4,'stalker',101,['spirit','dream']),
  m('dream-prison','sleep-lawyer','Sleep Lawyer','l','#bba0cf',36,15,3,'caster',101,['spirit','caster','dream'],[{op:'status',id:'confused',duration:4}]),
  m('dream-prison','door-eater','Door Eater','D','#8f7baa',55,16,7,'brute',101,['aberrant','dream']),
  m('star-forge','flare-hound','Flare Hound','h','#db9f5d',41,17,4,'stalker',101,['fire','beast','resist:fire']),
  m('star-forge','anvil-seraph','Anvil Seraph','A','#e6b66a',47,17,6,'caster',101,['fire','construct','caster','resist:fire'],[{op:'damage',amount:10,damageType:'fire'}]),
  m('star-forge','gravity-ox','Gravity Ox','O','#bd8f5f',65,18,8,'brute',101,['construct','star'],[{op:'push',distance:3}]),

  m('abyss','turnless-pilgrim','Turnless Pilgrim','p','#aa83c6',52,17,4,'stalker',1,['void','spirit','resist:void']),
  m('abyss','wrong-angle','Wrong Angle','A','#c78bdd',61,18,6,'skirmisher',1,['void','aberrant','resist:void'],[{op:'teleport',radius:4}]),
  m('abyss','starved-clock','Starved Clock','C','#a17ab9',68,18,8,'guard',1,['void','construct','resist:void']),
  m('abyss','echo-of-floor-zero','Echo of Floor Zero','0','#d697e3',58,19,5,'caster',1,['void','spirit','caster','resist:void'],[{op:'status',id:'unmoored',duration:4}]),
  m('abyss','map-eater','Map Eater','M','#e17baa',72,20,6,'brute',1,['void','aberrant','resist:void'],[{op:'damage',amount:11,damageType:'void'}]),
  m('abyss','hunger-with-legs','Hunger With Legs','H','#df6f98',78,21,7,'stalker',1,['void','aberrant','resist:void'],[{op:'status',id:'slowed',duration:3}]),
];
