import type { AiProfile, EffectSpec, MonsterDefinition, ThemeDefinition } from '../core/types';
import { EXTRA_MONSTERS } from './extra-monsters';
import { FOUNDATION_MONSTERS } from './foundation-monsters';
interface MonsterSeed { name:string; glyph:string; color:string; hp:number; attack:number; defense:number; ai:AiProfile; tags:string[]; ability?:EffectSpec; }
const seed=(name:string,glyph:string,color:string,hp:number,attack:number,defense:number,ai:AiProfile,tags:string[],ability?:EffectSpec):MonsterSeed=>({name,glyph,color,hp,attack,defense,ai,tags,...(ability?{ability}:{})});
const CATALOG:Array<{themeId:string;entries:MonsterSeed[]}>= [
{themeId:'moss-cistern',entries:[seed('Moss Rat','r','#94a873',7,3,0,'swarm',['beast','vermin']),seed('Cistern Slime','j','#84a96b',12,4,1,'brute',['ooze']),seed('Lantern Toad','f','#b4c77d',9,3,1,'skirmisher',['beast'],{op:'status',id:'dazed',duration:1})]},
{themeId:'drowned-aqueduct',entries:[seed('Silt Eel','e','#6eafbc',10,4,0,'skirmisher',['aquatic']),seed('Drowned Porter','z','#79949a',16,5,2,'stalker',['undead']),seed('Lockjaw Crab','c','#9a826d',18,5,3,'guard',['aquatic'],{op:'status',id:'pinned',duration:1})]},
{themeId:'ember-mine',entries:[seed('Coal Mite','m','#b27b55',8,4,0,'swarm',['vermin']),seed('Kiln Hound','h','#e28a4b',14,6,1,'stalker',['beast','fire']),seed('Ore Warden','g','#a58b75',22,6,4,'guard',['construct'])]},
{themeId:'fungal-vault',entries:[seed('Sporeling','s','#c1b667',9,4,0,'swarm',['fungal']),seed('Shelfback','t','#8d9b67',20,5,3,'brute',['fungal','beast']),seed('Puff Oracle','p','#d0c38a',13,5,1,'caster',['fungal','caster'],{op:'status',id:'confused',duration:2})]},
{themeId:'ossuary-terraces',entries:[seed('Bone Clerk','z','#c7bea8',15,5,2,'stalker',['undead']),seed('Urn Wisp','w','#d9d1bb',11,6,0,'skirmisher',['spirit']),seed('Sepulcher Knight','K','#b8ad96',28,8,5,'guard',['undead','humanoid'])]},
{themeId:'ironwarren',entries:[seed('Rivet Goblin','g','#a38463',15,6,2,'stalker',['humanoid']),seed('Chain Beetle','b','#90979a',18,6,4,'brute',['vermin','construct']),seed('Press Automaton','A','#b7a27a',30,9,6,'guard',['construct'],{op:'push',distance:2})]},
{themeId:'crystal-hollows',entries:[seed('Shard Hare','r','#a5b9e2',12,6,1,'skirmisher',['beast','crystal']),seed('Resonant Golem','G','#9eb0d5',30,8,6,'brute',['construct','crystal']),seed('Prism Shade','S','#c7b6e8',18,8,2,'caster',['spirit','crystal'],{op:'teleport',radius:4})]},
{themeId:'venom-fen',entries:[seed('Bog Needle','v','#9bb85d',13,6,1,'skirmisher',['venom','plant']),seed('Mire Crocodile','C','#789259',28,9,4,'stalker',['aquatic','beast']),seed('Fume Idol','i','#a8bd6d',24,7,5,'guard',['venom','construct'],{op:'status',id:'poisoned',duration:4,magnitude:2})]},
{themeId:'storm-archive',entries:[seed('Paper Moth','m','#c7cbe2',11,6,0,'swarm',['vermin']),seed('Volt Scribe','s','#abb8df',18,8,2,'caster',['caster','humanoid'],{op:'damage',amount:4,damageType:'shock'}),seed('Index Sentinel','I','#9ca7c4',32,9,6,'guard',['construct'])]},
{themeId:'ash-cathedral',entries:[seed('Censer Ghoul','z','#ad9384',23,8,3,'stalker',['undead']),seed('Ash Deacon','d','#c2a38f',20,9,2,'caster',['humanoid','fire'],{op:'status',id:'blinded',duration:2}),seed('Charred Gargoyle','G','#8d8079',34,10,7,'guard',['construct','fire'])]},
{themeId:'flesh-cloister',entries:[seed('Vein Leech','l','#c97882',14,7,1,'swarm',['flesh','vermin']),seed('Choir Maw','M','#dc8790',29,10,3,'brute',['flesh','aberrant']),seed('Nerve Apostle','n','#d99ba1',24,9,2,'caster',['flesh','caster'],{op:'status',id:'slowed',duration:2})]},
{themeId:'clockwork-necropolis',entries:[seed('Grave Gear','o','#b09869',18,8,4,'swarm',['construct']),seed('Pendulum Corpse','z','#a6987e',28,10,4,'brute',['undead','construct']),seed('Mortuary Engine','E','#c2a96e',40,12,7,'guard',['construct','undead'],{op:'summon',tag:'undead',count:1})]},
{themeId:'frozen-observatory',entries:[seed('Rime Familiar','f','#b8d8e4',16,8,1,'skirmisher',['ice','spirit']),seed('Lens Keeper','k','#afc5ce',27,10,4,'guard',['construct']),seed('White Comet','*','#e2f6ff',22,11,2,'caster',['ice','spirit'],{op:'status',id:'chilled',duration:3})]},
{themeId:'sunken-palace',entries:[seed('Pearl Guard','g','#9dc2ba',30,10,5,'guard',['humanoid','aquatic']),seed('Court Lamprey','l','#72aab0',18,9,1,'stalker',['aquatic']),seed('Tide Revenant','R','#82aeb0',33,12,4,'caster',['undead','aquatic'],{op:'push',distance:2})]},
{themeId:'void-garden',entries:[seed('Star Orchid','y','#b7a4db',20,9,2,'guard',['plant','void']),seed('Hollow Stag','H','#9f8fc4',31,12,3,'stalker',['beast','aberrant']),seed('Night Gardener','N','#c09bd0',27,11,3,'caster',['plant','spirit'],{op:'teleport',radius:5})]},
{themeId:'royal-chasm',entries:[seed('Crownless Guard','K','#bd9d75',36,12,6,'guard',['humanoid','undead']),seed('Banner Wraith','W','#c1a68d',26,12,2,'skirmisher',['spirit']),seed('Chasm Lion','L','#d1ae74',38,14,4,'stalker',['beast'])]},
{themeId:'dream-prison',entries:[seed('Sleepless Inmate','i','#aa9cc7',28,11,3,'stalker',['humanoid','spirit']),seed('Cell Dream','D','#c3a7d8',34,13,3,'caster',['aberrant','spirit'],{op:'status',id:'confused',duration:3}),seed('Warden of Doors','W','#9e91bc',44,14,7,'guard',['aberrant'])]},
{themeId:'star-forge',entries:[seed('Solar Rivet','*','#f2c676',20,11,2,'swarm',['fire','construct']),seed('Forge Seraph','A','#e5b76d',38,14,5,'caster',['fire','construct'],{op:'damage',amount:7,damageType:'fire'}),seed('Core Smith','S','#d6995f',48,16,8,'brute',['construct','humanoid'])]},
];
export const MONSTERS:MonsterDefinition[]=CATALOG.flatMap((group,themeIndex)=>group.entries.map((entry)=>({id:`${group.themeId}-${entry.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,name:entry.name,glyph:entry.glyph,color:entry.color,maxHp:entry.hp,attack:entry.attack,defense:entry.defense,ai:entry.ai,tags:[...entry.tags,`theme:${group.themeId}`],minDepth:themeIndex===17?101:Math.floor(themeIndex/3)*20+1,abilities:entry.ability?[entry.ability]:[]})));
MONSTERS.push(
{id:'abyss-folded-witness',name:'Folded Witness',glyph:'W',color:'#d39ae8',maxHp:42,attack:15,defense:4,ai:'caster',tags:['void','aberrant','theme:abyss'],minDepth:1,abilities:[{op:'teleport',radius:6}]},
{id:'abyss-edge-eater',name:'Edge Eater',glyph:'E',color:'#ef7ba6',maxHp:56,attack:18,defense:6,ai:'brute',tags:['void','aberrant','theme:abyss'],minDepth:1,abilities:[{op:'damage',amount:9,damageType:'void'}]},
{id:'abyss-unperson',name:'Unperson',glyph:'@',color:'#b28ac8',maxHp:34,attack:14,defense:3,ai:'stalker',tags:['void','spirit','theme:abyss'],minDepth:1,abilities:[{op:'status',id:'unmoored',duration:3}]});
MONSTERS.push(...EXTRA_MONSTERS,...FOUNDATION_MONSTERS);
export function monstersForTheme(theme:ThemeDefinition,depth:number):MonsterDefinition[]{const direct=MONSTERS.filter((m)=>m.tags.includes(`theme:${theme.id}`)&&m.minDepth<=depth+20);if(direct.length)return direct;return MONSTERS.filter((m)=>m.tags.some((tag)=>theme.monsterTags.includes(tag))&&m.minDepth<=depth+20);}
export function monsterById(id:string):MonsterDefinition{const found=MONSTERS.find((m)=>m.id===id);if(!found)throw new Error(`unknown monster: ${id}`);return found;}
