import { DeterministicRng, deriveSeed, hashString32 } from './rng';
import type { GameState, GroundItem, MonsterEntity, Point, StoryEvent, WorldCoord } from './types';
import { generateFloor, exitAt, tileAt } from '../world/generation';
import { resolveThemeContext } from '../world/themes';
import { monsterById, monstersForTheme } from '../content/monsters';
import { ITEMS } from '../content/items';
import { milestoneEvent, themeDiscoveryEvent } from './story';
const MAX_MESSAGES=7;
function id(prefix:string,rng:DeterministicRng):string{return `${prefix}-${rng.nextU32().toString(36)}-${rng.nextU32().toString(36)}`;}
function pushMessage(state:GameState,message:string):void{state.messages.push(message);if(state.messages.length>MAX_MESSAGES)state.messages.splice(0,state.messages.length-MAX_MESSAGES);}
function pointKey(point:Point):string{return `${point.x},${point.y}`;}
function walkableFreePoints(state:GameState):Point[]{const occupied=new Set<string>([pointKey(state.player),...state.floor.exits.map(pointKey)]);return state.floor.tiles.flatMap((tile,index)=>{if(!tile.walkable)return[];const point={x:index%state.floor.width,y:Math.floor(index/state.floor.width)};return occupied.has(pointKey(point))?[]:[point];});}
function populateFloor(state:GameState,rng:DeterministicRng):void{const context=resolveThemeContext(state.coord),candidates=monstersForTheme(context.primary,state.coord.depth),points=rng.shuffle(walkableFreePoints(state));const monsterCount=Math.min(points.length,rng.int(6,10)+Math.floor(state.coord.depth/25));state.monsters=[];for(let i=0;i<monsterCount;i+=1){const def=rng.pick(candidates),point=points.pop();if(!point)break;state.monsters.push({id:id('m',rng),defId:def.id,hp:def.maxHp,...point});}state.items=[];for(let i=0;i<rng.int(2,5);i+=1){const def=rng.weighted(ITEMS.map((itemDef)=>({value:itemDef,weight:1/Math.max(1,itemDef.rarity)}))),point=points.pop();if(!point)break;state.items.push({id:id('i',rng),defId:def.id,...point});}}
function createFloorState(state:GameState):void{const context=resolveThemeContext(state.coord);state.themeId=context.primary.id;state.floor=generateFloor(state.runSeed,state.coord,context);state.player.x=state.floor.spawn.x;state.player.y=state.floor.spawn.y;populateFloor(state,new DeterministicRng(deriveSeed(state.runSeed,state.coord.depth,state.coord.lane,'population')));}
export function createNewGame(seedText:string):{state:GameState;event:StoryEvent|null}{const runSeed=hashString32(seedText.trim()||`${Date.now()}`),runRng=new DeterministicRng(deriveSeed(runSeed,'run')),coord:WorldCoord={depth:1,lane:0},context=resolveThemeContext(coord),floor=generateFloor(runSeed,coord,context);const state:GameState={schemaVersion:1,runId:`run-${runSeed.toString(16)}-${runRng.nextU32().toString(36)}`,runSeed,turn:0,rngState:runRng.state,coord,themeId:context.primary.id,discoveredThemes:[],seenStoryEvents:[],floor,player:{id:'player',x:floor.spawn.x,y:floor.spawn.y,hp:30,maxHp:30,attack:6,defense:1,inventory:[]},monsters:[],items:[],messages:['You descend beneath the cistern.'],gameOver:false};populateFloor(state,new DeterministicRng(deriveSeed(runSeed,coord.depth,coord.lane,'population')));const event=themeDiscoveryEvent(state,context.primary);if(event)applyStoryEvent(state,event);return{state,event};}
function applyStoryEvent(state:GameState,event:StoryEvent):void{if(!state.seenStoryEvents.includes(event.id))state.seenStoryEvents.push(event.id);if(event.id.startsWith('theme:')){const themeId=event.id.slice('theme:'.length);if(!state.discoveredThemes.includes(themeId))state.discoveredThemes.push(themeId);}if(event.id==='enter-abyss'&&!state.discoveredThemes.includes('abyss'))state.discoveredThemes.push('abyss');}
function transition(state:GameState,kind:'down'|'drift-left'|'drift-right'):StoryEvent|null{state.coord.depth+=1;if(kind==='drift-left')state.coord.lane-=1;if(kind==='drift-right')state.coord.lane+=1;const previousTheme=state.themeId;createFloorState(state);pushMessage(state,kind==='down'?'You descend.':kind==='drift-left'?'You take the western descent.':'You take the eastern descent.');const context=resolveThemeContext(state.coord),themeEvent=context.primary.id!==previousTheme?themeDiscoveryEvent(state,context.primary):null,event=themeEvent??milestoneEvent(state);if(event)applyStoryEvent(state,event);return event;}
function monsterAt(state:GameState,x:number,y:number):MonsterEntity|undefined{return state.monsters.find((monster)=>monster.x===x&&monster.y===y);}
function itemAt(state:GameState,x:number,y:number):GroundItem|undefined{return state.items.find((item)=>item.x===x&&item.y===y);}
function attackMonster(state:GameState,monster:MonsterEntity,rng:DeterministicRng):void{const def=monsterById(monster.defId),damage=Math.max(1,state.player.attack+rng.int(-1,2)-def.defense);monster.hp-=damage;pushMessage(state,`You hit ${def.name} for ${damage}.`);if(monster.hp<=0){state.monsters=state.monsters.filter((entry)=>entry.id!==monster.id);pushMessage(state,`${def.name} dies.`);}}
function moveMonsters(state:GameState,rng:DeterministicRng):void{const occupied=new Set(state.monsters.map(pointKey));for(const monster of state.monsters){const def=monsterById(monster.defId),distance=Math.abs(monster.x-state.player.x)+Math.abs(monster.y-state.player.y);if(distance===1){const damage=Math.max(1,def.attack+rng.int(-1,1)-state.player.defense);state.player.hp-=damage;pushMessage(state,`${def.name} hits you for ${damage}.`);if(state.player.hp<=0){state.player.hp=0;state.gameOver=true;pushMessage(state,'You die beneath the world.');return;}continue;}if(distance>13&&def.ai!=='stalker')continue;const dx=Math.sign(state.player.x-monster.x),dy=Math.sign(state.player.y-monster.y),options:Point[]=rng.chance(.5)?[{x:monster.x+dx,y:monster.y},{x:monster.x,y:monster.y+dy}]:[{x:monster.x,y:monster.y+dy},{x:monster.x+dx,y:monster.y}];for(const target of options){if(target.x===state.player.x&&target.y===state.player.y)continue;const tile=tileAt(state.floor,target.x,target.y);if(!tile?.walkable||occupied.has(pointKey(target)))continue;occupied.delete(pointKey(monster));monster.x=target.x;monster.y=target.y;occupied.add(pointKey(monster));break;}}}
export function actMove(state:GameState,dx:number,dy:number):StoryEvent|null{if(state.gameOver)return null;if(Math.abs(dx)+Math.abs(dy)!==1)throw new Error('movement must be cardinal and one tile');const target={x:state.player.x+dx,y:state.player.y+dy},tile=tileAt(state.floor,target.x,target.y);if(!tile?.walkable)return null;const rng=new DeterministicRng(state.rngState),monster=monsterAt(state,target.x,target.y);if(monster)attackMonster(state,monster,rng);else{state.player.x=target.x;state.player.y=target.y;const item=itemAt(state,target.x,target.y);if(item){state.player.inventory.push(item.defId);state.items=state.items.filter((entry)=>entry.id!==item.id);pushMessage(state,`You pick up ${item.defId.replaceAll('-',' ')}.`);}}state.turn+=1;moveMonsters(state,rng);state.rngState=rng.state;if(state.gameOver)return null;const exit=exitAt(state.floor,state.player.x,state.player.y);return exit?transition(state,exit.kind):null;}
export function assertGameInvariants(state:GameState):void{if(!tileAt(state.floor,state.player.x,state.player.y)?.walkable)throw new Error('invariant: player must stand on walkable tile');const ids=new Set<string>();for(const entity of [state.player,...state.monsters,...state.items]){if(ids.has(entity.id))throw new Error(`invariant: duplicate entity id ${entity.id}`);ids.add(entity.id);}for(const monster of state.monsters){if(monster.hp<=0)throw new Error(`invariant: dead monster retained ${monster.id}`);if(!tileAt(state.floor,monster.x,monster.y)?.walkable)throw new Error(`invariant: monster in wall ${monster.id}`);}}
