import './tower2.css';
import { BAND_NAMES,FLOOR_NAMES,SKILL_NAMES,bandFor,createRun,labelEnemy,labelItem,moveHero,type HeroClass,type ItemKind,type TileKind,type TowerState,type Unit,useItem,useSkill,waitTurn } from './tower';
import { getRogueStatus,visibleSystemObjects,type Corpse,type DungeonFeature } from './nethack';

const app=document.querySelector<HTMLDivElement>('#app')!;
let state:TowerState|null=null;
let selected:HeroClass='vanguard';
let canvas:HTMLCanvasElement|null=null;
let autoTimer:number|undefined;
let skillTargeting=false;

const CLASS_INFO:Record<HeroClass,{name:string;tag:string;desc:string;accent:string}>={
  vanguard:{name:'VANGUARD',tag:'GUARD · FORCE',desc:'Hold doorways, build guard, and knock enemies out of useful positions.',accent:'#b79264'},
  ranger:{name:'RANGER',tag:'SEARCH · RANGE',desc:'Better at finding hidden things and strongest when a clean lane stays open.',accent:'#829c70'},
  arcanist:{name:'ARCANIST',tag:'BURST · CHAINS',desc:'Fragile spell pressure. Arc Bolt rewards enemies bunching together.',accent:'#9581b7'}
};

function title(){
  stopAuto();state=null;skillTargeting=false;
  app.innerHTML=`<main class="screen title-screen">
    <section class="title-head"><small>A SYSTEMIC TURN-BASED ROGUELIKE</small><h1>TOWER <span>OF THE FIRST KING</span></h1><p>Search the stone. Use what you find. Climb.</p></section>
    <div class="tower-silhouette" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><b></b></div>
    <section class="start-panel">
      <div class="class-grid">${(Object.keys(CLASS_INFO) as HeroClass[]).map(k=>{const v=CLASS_INFO[k];return`<button class="class-card ${selected===k?'selected':''}" data-class="${k}" style="--accent:${v.accent}"><span class="sigil ${k}"></span><strong>${v.name}</strong><small>${v.tag}</small></button>`}).join('')}</div>
      <p class="class-desc">${CLASS_INFO[selected].desc}</p>
      <button id="start" class="start-button">ENTER THE TOWER</button>
      <div class="title-help"><span>tap ground to move · tap enemies to strike</span><span>SEARCH / ACT matters</span></div>
    </section>
  </main>`;
  app.querySelectorAll<HTMLButtonElement>('[data-class]').forEach(b=>b.onclick=()=>{selected=b.dataset.class as HeroClass;title()});
  document.querySelector<HTMLButtonElement>('#start')!.onclick=()=>start(selected);
}

function start(cls:HeroClass){state=createRun(`first-king-${Date.now()}`,cls);game()}
function game(){
  app.innerHTML=`<main class="screen game-screen">
    <canvas id="game"></canvas>
    <header class="hud">
      <section class="hero-panel"><div class="hero-row"><b id="hpText"></b><span id="guardText"></span></div><div class="hp-bar"><i id="hpFill"></i></div><div class="survival-row"><span id="foodText"></span><span id="goldText"></span></div></section>
      <section class="floor-panel"><small id="bandName"></small><strong id="floorName"></strong><span id="floorNo"></span></section>
      <button id="menu" class="menu-btn">☰</button>
    </header>
    <div id="boss" class="boss-bar"></div>
    <div id="message" class="message"></div>
    <footer class="dock">
      <button id="skill" class="skill-btn"><b id="skillName"></b><small id="skillCd"></small></button>
      <div id="items" class="item-slots"></div>
      <button id="system" class="system-btn"><span>⌕</span><small id="systemLabel">SEARCH</small></button>
      <button id="pack" class="pack-btn"><span>▣</span><small>PACK</small></button>
    </footer>
    <div id="targetHint" class="target-hint hidden">SELECT A VISIBLE TARGET</div>
    <div id="overlay" class="overlay hidden"></div>
  </main>`;
  canvas=document.querySelector<HTMLCanvasElement>('#game')!;resize();window.onresize=resize;
  canvas.addEventListener('pointerdown',mapTap);
  document.querySelector<HTMLButtonElement>('#skill')!.onclick=toggleSkill;
  document.querySelector<HTMLButtonElement>('#system')!.onclick=()=>{if(!state)return;cancelSkill();stopAuto();waitTurn(state);afterAction()};
  document.querySelector<HTMLButtonElement>('#pack')!.onclick=showPack;
  document.querySelector<HTMLButtonElement>('#menu')!.onclick=showMenu;
  window.onkeydown=e=>{if(!state)return;const k=e.key.toLowerCase();if(['arrowup','w'].includes(k))moveBy(0,-1);else if(['arrowdown','s'].includes(k)&&k!=='s')moveBy(0,1);else if(['arrowleft','a'].includes(k))moveBy(-1,0);else if(['arrowright','d'].includes(k))moveBy(1,0);else if(k==='s'||k==='e'||k===' '){cancelSkill();stopAuto();waitTurn(state);afterAction()}else if(k==='q')toggleSkill()};
  render();updateHud();
}

function resize(){if(!canvas)return;const dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.floor(innerWidth*dpr);canvas.height=Math.floor(innerHeight*dpr);canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;render()}
function moveBy(dx:number,dy:number){if(!state)return;cancelSkill();stopAuto();moveHero(state,dx,dy);afterAction()}
function afterAction(){render();updateHud();if(state&&(state.dead||state.won))window.setTimeout(endScreen,260)}
function toggleSkill(){if(!state||state.hero.skillCooldown>0)return;skillTargeting=!skillTargeting;stopAuto();document.querySelector<HTMLElement>('#targetHint')?.classList.toggle('hidden',!skillTargeting);document.querySelector<HTMLButtonElement>('#skill')?.classList.toggle('armed',skillTargeting);render()}
function cancelSkill(){skillTargeting=false;document.querySelector<HTMLElement>('#targetHint')?.classList.add('hidden');document.querySelector<HTMLButtonElement>('#skill')?.classList.remove('armed')}

function showMenu(){cancelSkill();const o=document.querySelector<HTMLDivElement>('#overlay');if(!o)return;o.classList.remove('hidden');o.innerHTML=`<section class="modal"><small>PAUSED</small><h2>${state?FLOOR_NAMES[state.floor]??'Tower':''}</h2><button id="resume" class="action">RESUME</button><button id="quit" class="ghost">ABANDON RUN</button></section>`;document.querySelector<HTMLButtonElement>('#resume')!.onclick=()=>o.classList.add('hidden');document.querySelector<HTMLButtonElement>('#quit')!.onclick=title}
function endScreen(){if(!state)return;const o=document.querySelector<HTMLDivElement>('#overlay');if(!o)return;o.classList.remove('hidden');o.innerHTML=`<section class="modal"><small>${state.won?'THE CROWN OPENS':'ASCENT ENDED'}</small><h2>${state.won?'THE SKY ABOVE':'FLOOR '+state.floor}</h2><p>${state.won?'The final stair reaches daylight.':'The tower keeps what you learned.'}</p><button id="again" class="action">ASCEND AGAIN</button><button id="back" class="ghost">TITLE</button></section>`;document.querySelector<HTMLButtonElement>('#again')!.onclick=()=>start(selected);document.querySelector<HTMLButtonElement>('#back')!.onclick=title}
function itemDot(k:ItemKind){return`<span class="item-dot ${k}"></span>`}
function itemSub(k:ItemKind){return k==='potion'?'+13 HP':k==='bomb'?'nearby blast':k==='ration'?'food + recovery':k==='ward'?'+5 guard':k==='smoke'?'break enemy tempo':'7 ranged damage'}
function showPack(){if(!state)return;cancelSkill();const o=document.querySelector<HTMLDivElement>('#overlay');if(!o)return;o.classList.remove('hidden');o.innerHTML=`<section class="modal"><div class="pack-head"><div><small>TRAVEL PACK</small><h2>${state.hero.bag.length} ITEMS</h2></div><button id="close">×</button></div><div class="pack-list">${state.hero.bag.length?state.hero.bag.map((k,i)=>`<button class="pack-item" data-use="${i}">${itemDot(k)}<span><strong>${labelItem(k)}</strong><em>${itemSub(k)}</em></span><i>USE</i></button>`).join(''):'<p>Your pack is empty.</p>'}</div></section>`;document.querySelector<HTMLButtonElement>('#close')!.onclick=()=>o.classList.add('hidden');o.querySelectorAll<HTMLButtonElement>('[data-use]').forEach(b=>b.onclick=()=>{if(!state)return;useItem(state,Number(b.dataset.use));o.classList.add('hidden');afterAction()})}

function updateHud(){if(!state)return;const rs=getRogueStatus(state);const hp=document.querySelector<HTMLElement>('#hpText')!,guard=document.querySelector<HTMLElement>('#guardText')!,fill=document.querySelector<HTMLElement>('#hpFill')!;hp.textContent=`${state.hero.hp} / ${state.hero.maxHp}`;guard.textContent=state.hero.guard?`GUARD ${state.hero.guard}`:'';fill.style.width=`${Math.max(0,state.hero.hp/state.hero.maxHp*100)}%`;const food=document.querySelector<HTMLElement>('#foodText')!;food.textContent=`FOOD ${rs.foodState}`;food.className=rs.foodState.toLowerCase();document.querySelector<HTMLElement>('#goldText')!.textContent=`${rs.gold}g`;document.querySelector<HTMLElement>('#bandName')!.textContent=BAND_NAMES[bandFor(state.floor)]??'';document.querySelector<HTMLElement>('#floorName')!.textContent=FLOOR_NAMES[state.floor]??'Unknown';document.querySelector<HTMLElement>('#floorNo')!.textContent=`${String(state.floor).padStart(2,'0')} / 20`;document.querySelector<HTMLElement>('#message')!.textContent=state.messages[state.messages.length-1]??'';
  const boss=state.enemies.find(e=>e.kind==='boss'),be=document.querySelector<HTMLElement>('#boss')!;if(boss){be.innerHTML=`<span>${bossName(boss)}</span><div><i style="width:${Math.max(0,boss.hp/boss.maxHp*100)}%"></i></div>`;be.classList.add('show')}else be.classList.remove('show');
  const skill=document.querySelector<HTMLButtonElement>('#skill')!;document.querySelector<HTMLElement>('#skillName')!.textContent=SKILL_NAMES[state.hero.cls];document.querySelector<HTMLElement>('#skillCd')!.textContent=state.hero.skillCooldown?`READY IN ${state.hero.skillCooldown}`:'READY';skill.classList.toggle('ready',state.hero.skillCooldown===0);
  const objs=visibleSystemObjects(state),here=objs.corpses.some(c=>c.x===state!.hero.x&&c.y===state!.hero.y)||objs.features.some(f=>f.x===state!.hero.x&&f.y===state!.hero.y&&f.kind!=='door')||objs.features.some(f=>f.kind==='door'&&f.locked&&!f.open&&Math.abs(f.x-state!.hero.x)+Math.abs(f.y-state!.hero.y)===1);document.querySelector<HTMLElement>('#systemLabel')!.textContent=here?'ACT':'SEARCH';
  const items=document.querySelector<HTMLDivElement>('#items')!;items.innerHTML='';for(let i=0;i<4;i++){const k=state.hero.bag[i],b=document.createElement('button');b.className='slot';b.innerHTML=k?`${itemDot(k)}<small>${labelItem(k).split(' ')[0]}</small>`:`<span class="item-dot"></span><small>EMPTY</small>`;if(k)b.onclick=()=>{if(!state)return;cancelSkill();stopAuto();useItem(state,i);afterAction()};items.appendChild(b)}
}
function bossName(e:Unit){const b=e.bossBand??bandFor(state?.floor??1);return b===1?'WARDEN OF THE GATE':b===2?'THE IRON CAPTAIN':b===3?'THE VERDANT THRONE':b===4?'THE CURATOR':'ECHO OF THE FIRST KING'}

function mapTap(ev:PointerEvent){if(!state||!canvas)return;const p=screenToWorld(ev.clientX,ev.clientY);if(!p)return;const enemy=state.enemies.find(e=>e.x===p.x&&e.y===p.y);if(skillTargeting){if(enemy&&useSkill(state,p.x,p.y)){cancelSkill();afterAction()}return}if(enemy&&Math.abs(enemy.x-state.hero.x)+Math.abs(enemy.y-state.hero.y)===1){stopAuto();moveHero(state,enemy.x-state.hero.x,enemy.y-state.hero.y);afterAction();return}autoWalk(p.x,p.y)}
function view(){if(!canvas)return{ts:48,ox:0,oy:0};const ts=Math.max(38,Math.min(60,Math.floor(Math.min(canvas.width/10.2,canvas.height/15.8))));return{ts,ox:canvas.width/2-ts*.5,oy:canvas.height*.505-ts*.5}}
function screenToWorld(sx:number,sy:number){if(!state||!canvas)return null;const dpr=canvas.width/innerWidth,v=view();return{x:Math.floor((sx*dpr-v.ox)/v.ts+state.hero.x),y:Math.floor((sy*dpr-v.oy)/v.ts+state.hero.y)}}
function pathStep(tx:number,ty:number){if(!state)return null;const s=state;if(tx<0||ty<0||tx>=s.w||ty>=s.h)return null;const goal=ty*s.w+tx,start=s.hero.y*s.w+s.hero.x,prev=new Int32Array(s.w*s.h);prev.fill(-2);prev[start]=-1;const q=[start];for(let h=0;h<q.length;h++){const cur=q[h]!;if(cur===goal)break;const x=cur%s.w,y=Math.floor(cur/s.w);for(const[dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]] as const){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=s.w||ny>=s.h)continue;const ni=ny*s.w+nx;if(prev[ni]!==-2)continue;const t=s.tiles[ni];if(!t||['wall','void','chasm','books','pillar'].includes(t.kind))continue;if(s.enemies.some(e=>e.x===nx&&e.y===ny)&&ni!==goal)continue;prev[ni]=cur;q.push(ni)}}if(prev[goal]===-2)return null;let cur=goal;while(prev[cur]!==start&&prev[cur]>=0)cur=prev[cur]!;return{x:cur%s.w,y:Math.floor(cur/s.w)}}
function threatNear(){return!!state&&state.enemies.some(e=>Math.abs(e.x-state!.hero.x)+Math.abs(e.y-state!.hero.y)<=3)}
function autoWalk(tx:number,ty:number){if(!state)return;stopAuto();const startFloor=state.floor;const tick=()=>{if(!state||state.dead||state.won||state.floor!==startFloor){stopAuto();return}const p=pathStep(tx,ty);if(!p){stopAuto();return}moveHero(state,p.x-state.hero.x,p.y-state.hero.y);afterAction();if((state.hero.x===tx&&state.hero.y===ty)||threatNear()){stopAuto();return}autoTimer=window.setTimeout(tick,84)};tick()}
function stopAuto(){if(autoTimer!==undefined){clearTimeout(autoTimer);autoTimer=undefined}}

function pal(b:number){if(b===1)return{f:'#514a3f',f2:'#5f5648',w:'#242522',w2:'#343630',e:'#887b67',a:'#ba9968'};if(b===2)return{f:'#41413c',f2:'#4d4c45',w:'#20211f',w2:'#30322f',e:'#7f7668',a:'#ad8f5e'};if(b===3)return{f:'#344239',f2:'#405044',w:'#1c2923',w2:'#2a3a31',e:'#718b76',a:'#c1a966'};if(b===4)return{f:'#34343e',f2:'#41404b',w:'#1e1f28',w2:'#2c2d39',e:'#77758e',a:'#b69a6b'};return{f:'#302d37',f2:'#403a47',w:'#191820',w2:'#292631',e:'#81738c',a:'#d1aa62'}}
function render(){if(!state||!canvas)return;const c=canvas.getContext('2d')!,v=view(),b=bandFor(state.floor),p=pal(b);c.imageSmoothingEnabled=false;c.fillStyle=b===5?'#05040a':'#060707';c.fillRect(0,0,canvas.width,canvas.height);for(let y=0;y<state.h;y++)for(let x=0;x<state.w;x++){const t=state.tiles[y*state.w+x];if(!t?.seen)continue;const sx=v.ox+(x-state.hero.x)*v.ts,sy=v.oy+(y-state.hero.y)*v.ts;if(sx<-v.ts||sy<-v.ts||sx>canvas.width||sy>canvas.height)continue;drawTile(c,sx,sy,v.ts,t.kind,t.variant,p,t.visible)}drawSystems(c,v);drawIntents(c,v);for(const d of state.drops){if(state.tiles[d.y*state.w+d.x]?.visible)drawDrop(c,v.ox+(d.x-state.hero.x)*v.ts,v.oy+(d.y-state.hero.y)*v.ts,v.ts,d.kind)}for(const e of state.enemies){if(state.tiles[e.y*state.w+e.x]?.visible)drawEnemy(c,v.ox+(e.x-state.hero.x)*v.ts,v.oy+(e.y-state.hero.y)*v.ts,v.ts,e)}drawHero(c,v.ox,v.oy,v.ts,state.hero.cls);if(skillTargeting)drawSkillTargets(c,v);const g=c.createRadialGradient(canvas.width*.5,canvas.height*.5,Math.min(canvas.width,canvas.height)*.18,canvas.width*.5,canvas.height*.5,Math.max(canvas.width,canvas.height)*.72);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(.7,'rgba(0,0,0,.08)');g.addColorStop(1,'rgba(0,0,0,.72)');c.fillStyle=g;c.fillRect(0,0,canvas.width,canvas.height)}
function drawTile(c:CanvasRenderingContext2D,x:number,y:number,s:number,k:TileKind,v:number,p:ReturnType<typeof pal>,visible:boolean){const dim=visible?1:.34;c.save();c.globalAlpha=dim;if(k==='void'){c.restore();return}if(k==='chasm'){c.fillStyle='#020307';c.fillRect(x,y,s,s);c.strokeStyle='rgba(159,160,190,.13)';c.beginPath();c.moveTo(x+s*.1,y+s*.45);c.lineTo(x+s*.36,y+s*.38);c.lineTo(x+s*.58,y+s*.62);c.lineTo(x+s*.9,y+s*.51);c.stroke();c.restore();return}if(k==='wall'){c.fillStyle=p.w;c.fillRect(x,y,s,s);c.fillStyle=p.w2;c.fillRect(x+2,y+2,s-4,s*.63);c.fillStyle='#0b0c0b';c.fillRect(x,y+s*.72,s,s*.28);c.fillStyle=p.e;c.globalAlpha=dim*.28;c.fillRect(x+2,y+2,s-4,2);c.fillRect(x+3,y+s*.67,s-6,2);c.restore();return}c.fillStyle=p.f;c.fillRect(x,y,s,s);c.fillStyle=p.f2;c.globalAlpha=dim*.22;c.fillRect(x+2,y+2,s-4,s-4);c.globalAlpha=dim;c.strokeStyle='rgba(230,220,195,.07)';c.beginPath();c.moveTo(x+2,y+s*.48);c.lineTo(x+s-2,y+s*.48);c.moveTo(x+s*.57,y+2);c.lineTo(x+s*.57,y+s*.48);c.stroke();if(k==='door'){c.fillStyle='#5f422b';c.fillRect(x+s*.22,y+s*.12,s*.56,s*.76);c.fillStyle='#22170f';c.fillRect(x+s*.47,y+s*.46,s*.07,s*.09)}else if(k==='stairs'){for(let i=0;i<5;i++){c.fillStyle=i%2?p.e:p.f2;c.fillRect(x+s*(.14+i*.04),y+s*(.72-i*.11),s*(.72-i*.08),s*.07)}c.fillStyle=p.a;c.fillRect(x+s*.46,y+s*.12,s*.08,s*.25)}else if(k==='water'){c.fillStyle='#31575a';c.globalAlpha=dim*.8;c.fillRect(x+1,y+1,s-2,s-2);c.strokeStyle='rgba(174,219,205,.35)';c.beginPath();c.moveTo(x+s*.14,y+s*.58);c.quadraticCurveTo(x+s*.38,y+s*.48,x+s*.62,y+s*.58);c.quadraticCurveTo(x+s*.78,y+s*.64,x+s*.9,y+s*.58);c.stroke()}else if(k==='grass'){c.strokeStyle='#718660';for(let i=0;i<5;i++){const xx=x+s*(.18+i*.15);c.beginPath();c.moveTo(xx,y+s*.78);c.lineTo(xx-s*.04,y+s*(.45+(i%2)*.1));c.stroke()}}else if(k==='lava'){c.fillStyle='#3f1b15';c.fillRect(x+1,y+1,s-2,s-2);c.strokeStyle='#da7040';c.lineWidth=2;c.beginPath();c.moveTo(x+s*.1,y+s*.7);c.bezierCurveTo(x+s*.34,y+s*.2,x+s*.58,y+s*.88,x+s*.9,y+s*.3);c.stroke()}else if(k==='books'){c.fillStyle='#211a20';c.fillRect(x+s*.09,y+s*.1,s*.82,s*.8);for(let i=0;i<4;i++){c.fillStyle=['#70483b','#4d5d4d','#665470','#806c44'][i]!;c.fillRect(x+s*(.16+i*.17),y+s*.18,s*.11,s*.58)}}else if(k==='pillar'){c.fillStyle='#656052';c.fillRect(x+s*.34,y+s*.18,s*.32,s*.55);c.fillStyle='#817764';c.fillRect(x+s*.28,y+s*.13,s*.44,s*.1);c.fillStyle='#252621';c.beginPath();c.ellipse(x+s*.5,y+s*.77,s*.28,s*.1,0,0,Math.PI*2);c.fill()}else if(k==='gear'){c.strokeStyle='#a57a4c';c.lineWidth=2;c.beginPath();c.arc(x+s*.5,y+s*.5,s*.22,0,Math.PI*2);c.stroke()}else if(k==='rubble'){c.fillStyle='#35312c';for(let i=0;i<4;i++){c.beginPath();c.arc(x+s*(.25+i*.16),y+s*(.58+(i%2)*.08),s*.1,0,Math.PI*2);c.fill()}}else if(k==='trap'){c.strokeStyle='rgba(180,154,108,.25)';c.beginPath();c.moveTo(x+s*.2,y+s*.7);c.lineTo(x+s*.5,y+s*.32);c.lineTo(x+s*.8,y+s*.7);c.closePath();c.stroke()}c.restore()}
function drawSystems(c:CanvasRenderingContext2D,v:{ts:number;ox:number;oy:number}){if(!state)return;const o=visibleSystemObjects(state);for(const f of o.features){const x=v.ox+(f.x-state.hero.x)*v.ts,y=v.oy+(f.y-state.hero.y)*v.ts;drawFeature(c,x,y,v.ts,f)}for(const corpse of o.corpses){const x=v.ox+(corpse.x-state.hero.x)*v.ts,y=v.oy+(corpse.y-state.hero.y)*v.ts;drawCorpse(c,x,y,v.ts,corpse)}}
function drawFeature(c:CanvasRenderingContext2D,x:number,y:number,s:number,f:DungeonFeature){c.save();if(f.kind==='door'){if(f.open){c.strokeStyle='rgba(174,134,84,.55)';c.lineWidth=2;c.strokeRect(x+s*.14,y+s*.12,s*.72,s*.76)}else if(f.locked){c.fillStyle='#d1a45d';c.fillRect(x+s*.45,y+s*.45,s*.11,s*.12)}c.restore();return}if(f.kind==='trap'){c.strokeStyle='#d4a75f';c.lineWidth=2;c.beginPath();c.moveTo(x+s*.2,y+s*.72);c.lineTo(x+s*.38,y+s*.38);c.lineTo(x+s*.5,y+s*.66);c.lineTo(x+s*.62,y+s*.38);c.lineTo(x+s*.8,y+s*.72);c.stroke()}else if(f.kind==='fountain'){c.fillStyle='#425966';c.beginPath();c.ellipse(x+s*.5,y+s*.68,s*.31,s*.13,0,0,Math.PI*2);c.fill();c.fillStyle='#7ea5aa';c.fillRect(x+s*.46,y+s*.28,s*.08,s*.34)}else if(f.kind==='altar'){c.fillStyle='#706b5d';c.fillRect(x+s*.27,y+s*.55,s*.46,s*.22);c.fillStyle='#91846a';c.fillRect(x+s*.34,y+s*.35,s*.32,s*.22);c.strokeStyle='#d0b36e';c.beginPath();c.moveTo(x+s*.5,y+s*.4);c.lineTo(x+s*.5,y+s*.52);c.moveTo(x+s*.44,y+s*.46);c.lineTo(x+s*.56,y+s*.46);c.stroke()}else if(f.kind==='boulder'){c.fillStyle='#5e5a52';c.beginPath();c.arc(x+s*.5,y+s*.55,s*.28,0,Math.PI*2);c.fill();c.strokeStyle='#8b8474';c.beginPath();c.moveTo(x+s*.33,y+s*.42);c.lineTo(x+s*.57,y+s*.35);c.lineTo(x+s*.69,y+s*.55);c.stroke()}else if(f.kind==='pit'){c.fillStyle='#050506';c.beginPath();c.ellipse(x+s*.5,y+s*.61,s*.32,s*.18,0,0,Math.PI*2);c.fill();c.strokeStyle='#3a342e';c.stroke()}else if(f.kind==='chest'){c.fillStyle='#65472d';c.fillRect(x+s*.25,y+s*.43,s*.5,s*.32);c.fillStyle='#9d794c';c.fillRect(x+s*.23,y+s*.38,s*.54,s*.12);c.fillStyle='#d0a85e';c.fillRect(x+s*.47,y+s*.51,s*.07,s*.12)}else if(f.kind==='merchant'){c.fillStyle='#342d32';c.beginPath();c.arc(x+s*.5,y+s*.34,s*.13,0,Math.PI*2);c.fill();c.beginPath();c.moveTo(x+s*.28,y+s*.72);c.lineTo(x+s*.39,y+s*.38);c.lineTo(x+s*.61,y+s*.38);c.lineTo(x+s*.72,y+s*.72);c.closePath();c.fill();c.fillStyle='#b79458';c.fillRect(x+s*.46,y+s*.32,s*.08,s*.05)}else if(f.kind==='engraving'){c.strokeStyle='#b4a27f';c.lineWidth=1;c.beginPath();c.moveTo(x+s*.25,y+s*.55);c.lineTo(x+s*.42,y+s*.42);c.lineTo(x+s*.55,y+s*.57);c.lineTo(x+s*.72,y+s*.39);c.stroke()}else if(f.kind==='gold'){c.fillStyle='#c7a34d';for(const[dx,dy]of [[.38,.58],[.54,.55],[.48,.68]] as const){c.beginPath();c.arc(x+s*dx,y+s*dy,s*.07,0,Math.PI*2);c.fill()}}c.restore()}
function drawCorpse(c:CanvasRenderingContext2D,x:number,y:number,s:number,corpse:Corpse){c.save();c.fillStyle='rgba(0,0,0,.38)';c.beginPath();c.ellipse(x+s*.5,y+s*.69,s*.28,s*.09,0,0,Math.PI*2);c.fill();c.strokeStyle=corpse.kind==='slime'?'#72906d':'#927866';c.lineWidth=3;c.beginPath();c.moveTo(x+s*.29,y+s*.55);c.lineTo(x+s*.48,y+s*.65);c.lineTo(x+s*.69,y+s*.5);c.moveTo(x+s*.38,y+s*.48);c.lineTo(x+s*.62,y+s*.68);c.stroke();c.restore()}
function drawDrop(c:CanvasRenderingContext2D,x:number,y:number,s:number,k:ItemKind){c.save();c.fillStyle='rgba(0,0,0,.4)';c.beginPath();c.ellipse(x+s*.5,y+s*.73,s*.2,s*.07,0,0,Math.PI*2);c.fill();const col=k==='potion'?'#d75e59':k==='bomb'?'#c68a47':k==='ration'?'#bda66f':k==='ward'?'#9bb8be':k==='smoke'?'#8b969a':'#d1cab8';c.fillStyle=col;if(k==='bomb'){c.beginPath();c.arc(x+s*.5,y+s*.56,s*.16,0,Math.PI*2);c.fill()}else if(k==='knife'){c.fillRect(x+s*.47,y+s*.3,s*.06,s*.38)}else{c.fillRect(x+s*.36,y+s*.38,s*.28,s*.28)}c.restore()}
function drawEnemy(c:CanvasRenderingContext2D,x:number,y:number,s:number,e:Unit){c.save();c.fillStyle='rgba(0,0,0,.5)';c.beginPath();c.ellipse(x+s*.5,y+s*.78,s*.25,s*.08,0,0,Math.PI*2);c.fill();const body=e.kind==='boss'?'#806653':e.kind==='wisp'?'#9bc6c0':e.kind==='slime'?'#6e936c':e.kind==='archer'?'#5e7257':e.kind==='cultist'||e.kind==='seer'?'#695875':e.kind==='golem'?'#746b5c':'#77716a';if(e.kind==='wisp'){const g=c.createRadialGradient(x+s*.5,y+s*.48,1,x+s*.5,y+s*.48,s*.25);g.addColorStop(0,'#ecf4df');g.addColorStop(.45,body);g.addColorStop(1,'rgba(80,120,120,0)');c.fillStyle=g;c.beginPath();c.arc(x+s*.5,y+s*.48,s*.25,0,Math.PI*2);c.fill()}else if(e.kind==='rat'){c.fillStyle=body;c.beginPath();c.ellipse(x+s*.48,y+s*.58,s*.24,s*.14,0,0,Math.PI*2);c.fill();c.beginPath();c.arc(x+s*.69,y+s*.54,s*.09,0,Math.PI*2);c.fill()}else{c.fillStyle=body;c.beginPath();c.arc(x+s*.5,y+s*.3,s*(e.kind==='boss'?.14:.11),0,Math.PI*2);c.fill();c.beginPath();c.moveTo(x+s*.31,y+s*.42);c.lineTo(x+s*.25,y+s*.73);c.lineTo(x+s*.75,y+s*.73);c.lineTo(x+s*.69,y+s*.42);c.closePath();c.fill()}if(e.elite&&e.kind!=='boss'){c.strokeStyle='#c5a060';c.lineWidth=2;c.beginPath();c.arc(x+s*.5,y+s*.45,s*.25,Math.PI*1.1,Math.PI*1.9);c.stroke()}c.restore();if(e.hp<e.maxHp){c.fillStyle='#160b0a';c.fillRect(x+s*.19,y+s*.08,s*.62,4);c.fillStyle='#bd5549';c.fillRect(x+s*.19,y+s*.08,s*.62*Math.max(0,e.hp/e.maxHp),4)}}
function drawHero(c:CanvasRenderingContext2D,x:number,y:number,s:number,cls:HeroClass){c.save();c.fillStyle='rgba(0,0,0,.55)';c.beginPath();c.ellipse(x+s*.5,y+s*.8,s*.27,s*.09,0,0,Math.PI*2);c.fill();c.fillStyle='#d7b18b';c.beginPath();c.arc(x+s*.5,y+s*.3,s*.12,0,Math.PI*2);c.fill();c.fillStyle=cls==='vanguard'?'#c6b39a':cls==='ranger'?'#879d78':'#9584b4';c.beginPath();c.moveTo(x+s*.31,y+s*.42);c.lineTo(x+s*.25,y+s*.75);c.lineTo(x+s*.75,y+s*.75);c.lineTo(x+s*.69,y+s*.42);c.closePath();c.fill();c.strokeStyle=cls==='arcanist'?'#cfb7e6':'#d0b77e';c.lineWidth=2;c.beginPath();c.moveTo(x+s*.72,y+s*.36);c.lineTo(x+s*.78,y+s*.73);c.stroke();c.restore()}
function drawIntents(c:CanvasRenderingContext2D,v:{ts:number;ox:number;oy:number}){if(!state)return;const mark=(x:number,y:number)=>{const sx=v.ox+(x-state!.hero.x)*v.ts,sy=v.oy+(y-state!.hero.y)*v.ts;c.fillStyle='rgba(205,75,54,.2)';c.fillRect(sx+2,sy+2,v.ts-4,v.ts-4);c.strokeStyle='rgba(235,101,74,.8)';c.lineWidth=2;c.strokeRect(sx+3,sy+3,v.ts-6,v.ts-6)};for(const e of state.enemies){if(!e.intent||!state.tiles[e.y*state.w+e.x]?.visible)continue;if(e.intent==='charge'){const tx=e.intentX??state.hero.x,ty=e.intentY??state.hero.y,dx=Math.sign(tx-e.x),dy=Math.sign(ty-e.y);for(let i=1;i<=3;i++)mark(e.x+dx*i,e.y+dy*i)}else if(e.intent==='smash'){for(const[dx,dy]of [[0,0],[1,0],[-1,0],[0,1],[0,-1]] as const)mark(e.x+dx,e.y+dy)}else{const tx=e.intentX??state.hero.x,ty=e.intentY??state.hero.y;mark(tx,ty);if(e.intent==='curse'||e.intent==='starfire')for(const[dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]] as const)mark(tx+dx,ty+dy)}}}
function drawSkillTargets(c:CanvasRenderingContext2D,v:{ts:number;ox:number;oy:number}){if(!state)return;for(const e of state.enemies){const d=Math.abs(e.x-state.hero.x)+Math.abs(e.y-state.hero.y),ok=state.hero.cls==='vanguard'?d===1:d<=(state.hero.cls==='ranger'?6:5);if(!ok||!state.tiles[e.y*state.w+e.x]?.visible)continue;const x=v.ox+(e.x-state.hero.x)*v.ts,y=v.oy+(e.y-state.hero.y)*v.ts;c.strokeStyle='#dbc17f';c.lineWidth=2;c.strokeRect(x+3,y+3,v.ts-6,v.ts-6)}}

title();
