import './style.css';
import { actMove, assertGameInvariants, createNewGame } from './core/game';
import { RunSaveStore } from './core/save';
import type { GameState, StoryEvent } from './core/types';
import { describeState, renderCanvas } from './ui/render';
const appElement=document.querySelector<HTMLDivElement>('#app');if(!appElement)throw new Error('missing #app');const app:HTMLDivElement=appElement;
const saveStore=new RunSaveStore(localStorage);let state:GameState|null=null;let sessionNonce:string|null=null;
function titleScreen(note=''):void{state=null;sessionNonce=null;app.innerHTML=`<section class="title-screen"><div class="title-card"><p class="eyebrow">DETERMINISTIC ASCII ROGUELIKE</p><h1>Below the Lateral Edge</h1><p class="subtitle">Descend. Drift sideways into other dungeon ecologies. Drift too far and the world gives way to the Abyss.</p>${note?`<p class="notice">${note}</p>`:''}<label>Run seed <input id="seed" autocomplete="off" value="${Math.random().toString(36).slice(2,10)}" /></label><div class="title-actions"><button id="new-run">New run</button><button id="continue" ${saveStore.hasSave()?'':'disabled'}>Continue</button></div><p class="save-warning">Anti-save-scum mode: a run is dirty while active. Only “Save & Quit” produces a resumable clean save. Closing/crashing mid-run forfeits that save.</p></div></section>`;document.querySelector<HTMLButtonElement>('#new-run')?.addEventListener('click',()=>{const seed=document.querySelector<HTMLInputElement>('#seed')?.value??'',created=createNewGame(seed);state=created.state;sessionNonce=saveStore.beginNewRun(state);gameScreen();if(created.event)showStory(created.event);});document.querySelector<HTMLButtonElement>('#continue')?.addEventListener('click',()=>{const loaded=saveStore.claimCleanSave();if(!loaded.ok){titleScreen(loaded.reason==='dirty'?'The previous session did not end cleanly. That run cannot be resumed.':`Save could not be loaded (${loaded.reason}).`);return;}state=loaded.state;sessionNonce=loaded.sessionNonce;gameScreen();});}
function gameScreen():void{if(!state)return;app.innerHTML=`<section class="game-shell"><header><div><strong>Below the Lateral Edge</strong><span id="status"></span></div><button id="save-quit">Save & Quit</button></header><div class="map-wrap"><canvas id="game-canvas"></canvas></div><section class="log" id="log"></section><section class="controls" aria-label="movement controls"><span></span><button data-move="0,-1">▲</button><span></span><button data-move="-1,0">◀</button><button class="wait" disabled>·</button><button data-move="1,0">▶</button><span></span><button data-move="0,1">▼</button><span></span></section><p class="legend"><span>@ you</span><span>&gt; descend</span><span>[ drift west</span><span>] drift east</span></p></section>`;document.querySelectorAll<HTMLButtonElement>('[data-move]').forEach((button)=>button.addEventListener('click',()=>{const[dx,dy]=button.dataset.move!.split(',').map(Number) as [number,number];doMove(dx,dy);}));document.querySelector<HTMLButtonElement>('#save-quit')?.addEventListener('click',cleanQuit);window.addEventListener('resize',redraw,{passive:true});redraw();}
function doMove(dx:number,dy:number):void{if(!state||!sessionNonce)return;const event=actMove(state,dx,dy);assertGameInvariants(state);saveStore.checkpointDirty(state,sessionNonce);redraw();if(state.gameOver){saveStore.invalidateRun();setTimeout(()=>titleScreen('The run ended.'),650);return;}if(event)showStory(event);}
function cleanQuit():void{if(!state||!sessionNonce)return;const ok=saveStore.saveAndQuitClean(state,sessionNonce);titleScreen(ok?'Run saved cleanly.':'Save lease mismatch; the run remains dirty.');}
function redraw():void{if(!state)return;const canvas=document.querySelector<HTMLCanvasElement>('#game-canvas'),status=document.querySelector<HTMLElement>('#status'),log=document.querySelector<HTMLElement>('#log');if(canvas)renderCanvas(canvas,state);if(status)status.textContent=describeState(state);if(log)log.innerHTML=state.messages.map((message)=>`<div>${message}</div>`).join('');}
function showStory(event:StoryEvent):void{document.querySelector('.story-modal')?.remove();const modal=document.createElement('div');modal.className='story-modal';modal.innerHTML=`<div class="story-card"><p class="eyebrow">EXCEPTIONAL EVENT</p><h2>${event.title}</h2><p>${event.body}</p><button>Continue</button></div>`;modal.querySelector('button')?.addEventListener('click',()=>modal.remove());document.body.appendChild(modal);}
window.addEventListener('keydown',(event)=>{if(!state)return;const movement:Record<string,[number,number]>={ArrowUp:[0,-1],w:[0,-1],W:[0,-1],k:[0,-1],ArrowDown:[0,1],s:[0,1],S:[0,1],j:[0,1],ArrowLeft:[-1,0],a:[-1,0],A:[-1,0],h:[-1,0],ArrowRight:[1,0],d:[1,0],D:[1,0],l:[1,0]};const delta=movement[event.key];if(!delta)return;event.preventDefault();doMove(delta[0],delta[1]);});
window.addEventListener('pagehide',()=>{if(state&&sessionNonce)saveStore.checkpointDirty(state,sessionNonce);});
titleScreen();
