import './style.css';
import { BAND_NAMES,FLOOR_NAMES,SKILL_NAMES,bandFor,createRun,labelEnemy,labelItem,moveHero,type EnemyKind,type HeroClass,type ItemKind,type TileKind,type TowerState,type Unit,useItem,useSkill,waitTurn } from './tower';

const app=document.querySelector<HTMLDivElement>('#app')!;
let state:TowerState|null=null;
let selected:HeroClass='vanguard';
let canvas:HTMLCanvasElement|null=null;
let titleCanvas:HTMLCanvasElement|null=null;
let autoTimer:number|undefined;
let skillTargeting=false;

const CLASS_INFO:Record<HeroClass,{name:string;tag:string;desc:string;accent:string}>={
  vanguard:{name:'VANGUARD',tag:'GUARD · FORCE',desc:'Hold ground, build guard, then smash enemies out of position.',accent:'#b68c5e'},
  ranger:{name:'RANGER',tag:'RANGE · TEMPO',desc:'Keep lanes open and punish enemies before they reach you.',accent:'#7e9b70'},
  arcanist:{name:'ARCANIST',tag:'BURST · CHAINS',desc:'Fragile, explosive, and strongest when enemies bunch together.',accent:'#8e7eb0'}
};

function showTitle(){
  stopAuto();state=null;skillTargeting=false;
  app.innerHTML=`<main class="title-screen">
    <canvas id="titleArt" class="title-art"></canvas>
    <div class="title-shade"></div>
    <section class="title-copy">
      <div class="eyebrow">ASCEND · ADAPT · SURVIVE</div>
      <h1>TOWER <small>OF THE</small><br>FIRST KING</h1>
      <p>Twenty floors above a dead kingdom.</p>
    </section>
    <section class="start-panel">
      <div class="class-strip">
        ${(Object.keys(CLASS_INFO) as HeroClass[]).map(k=>{const v=CLASS_INFO[k];return `<button class="class-card ${k===selected?'selected':''}" data-class="${k}" style="--accent:${v.accent}"><span class="class-sigil ${k}"></span><strong>${v.name}</strong><small>${v.tag}</small></button>`}).join('')}
      </div>
      <p class="class-desc">${CLASS_INFO[selected].desc}</p>
      <button id="newRun" class="new-run">ENTER THE TOWER <b>↑</b></button>
      <div class="title-foot"><span>tap ground to move · tap adjacent enemies to strike</span><span>20 FLOORS</span></div>
    </section>
  </main>`;
  titleCanvas=document.querySelector<HTMLCanvasElement>('#titleArt')!;
  drawTitleArt();
  app.querySelectorAll<HTMLButtonElement>('[data-class]').forEach(btn=>btn.onclick=()=>{selected=btn.dataset.class as HeroClass;showTitle()});
  document.querySelector<HTMLButtonElement>('#newRun')!.onclick=()=>startRun(selected);
  window.onresize=drawTitleArt;
}
function startRun(cls:HeroClass){state=createRun(`first-king-${Date.now()}`,cls);showGame()}

function showGame(){
  app.innerHTML=`<main class="game-shell">
    <canvas id="game"></canvas>
    <div class="screen-vignette"></div>
    <header class="hud-top">
      <div class="hero-panel">
        <span id="heroPortrait" class="hero-portrait"></span>
        <div class="hero-vitals"><div class="vital-row"><b id="hpText"></b><span id="guardText"></span></div><div class="hp-track"><i id="hpFill"></i></div></div>
      </div>
      <div class="floor-card"><small id="bandName"></small><strong id="floorName"></strong><span id="floorNo"></span></div>
      <button id="menuBtn" class="icon-button" aria-label="menu"><i></i><i></i><i></i></button>
    </header>
    <div id="bossBanner" class="boss-banner"></div>
    <div id="message" class="message"></div>
    <footer class="action-dock">
      <button id="skillBtn" class="skill-button"><span class="skill-glyph"></span><b id="skillName"></b><small id="skillCd"></small></button>
      <div id="items" class="item-slots"></div>
      <button id="waitBtn" class="utility-button"><span class="wait-glyph"></span><small>WAIT</small></button>
      <button id="bagBtn" class="utility-button"><span class="bag-glyph"></span><small>PACK</small></button>
    </footer>
    <div id="targetHint" class="target-hint hidden">SELECT A TARGET</div>
    <div id="overlay" class="overlay hidden"></div>
  </main>`;
  canvas=document.querySelector<HTMLCanvasElement>('#game')!;
  resize();window.onresize=resize;
  canvas.addEventListener('pointerdown',onMapTap);
  document.querySelector<HTMLButtonElement>('#waitBtn')!.onclick=()=>{if(state){cancelSkill();stopAuto();waitTurn(state);afterAction()}};
  document.querySelector<HTMLButtonElement>('#bagBtn')!.onclick=showPack;
  document.querySelector<HTMLButtonElement>('#menuBtn')!.onclick=showMenu;
  document.querySelector<HTMLButtonElement>('#skillBtn')!.onclick=toggleSkill;
  window.onkeydown=e=>{if(!state)return;const k=e.key.toLowerCase();if(['arrowup','w'].includes(k))moveBy(0,-1);else if(['arrowdown','s'].includes(k))moveBy(0,1);else if(['arrowleft','a'].includes(k))moveBy(-1,0);else if(['arrowright','d'].includes(k))moveBy(1,0);else if(k===' ') {cancelSkill();waitTurn(state);afterAction()}else if(k==='q')toggleSkill()};
  render();updateHud();
}
function resize(){if(!canvas)return;const dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.floor(innerWidth*dpr);canvas.height=Math.floor(innerHeight*dpr);canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;render()}
function moveBy(dx:number,dy:number){if(!state)return;cancelSkill();stopAuto();moveHero(state,dx,dy);afterAction()}
function afterAction(){render();updateHud();if(!state)return;if(state.dead||state.won)window.setTimeout(showEnd,260)}

function showEnd(){if(!state)return;const o=document.querySelector<HTMLDivElement>('#overlay')!;o.classList.remove('hidden');o.innerHTML=`<section class="modal-card end-card"><small>${state.won?'THE CROWN OPENS':'ASCENT ENDED'}</small><h2>${state.won?'THE SKY ABOVE':'FLOOR '+state.floor}</h2><p>${state.won?'The tower ends in daylight, not a throne.':'The First King keeps the height for another challenger.'}</p><button id="again">ASCEND AGAIN</button><button id="titleReturn" class="ghost">TITLE</button></section>`;document.querySelector<HTMLButtonElement>('#again')!.onclick=()=>startRun(selected);document.querySelector<HTMLButtonElement>('#titleReturn')!.onclick=showTitle}
function showMenu(){cancelSkill();const o=document.querySelector<HTMLDivElement>('#overlay')!;o.classList.remove('hidden');o.innerHTML=`<section class="modal-card menu-card"><small>PAUSED</small><h2>${state?(FLOOR_NAMES[state.floor]??'Tower'):''}</h2><button id="resume">RESUME</button><button id="restart" class="ghost">ABANDON RUN</button></section>`;document.querySelector<HTMLButtonElement>('#resume')!.onclick=()=>o.classList.add('hidden');document.querySelector<HTMLButtonElement>('#restart')!.onclick=showTitle}
function showPack(){if(!state)return;cancelSkill();const o=document.querySelector<HTMLDivElement>('#overlay')!;o.classList.remove('hidden');o.innerHTML=`<section class="modal-card pack-card"><header><div><small>TRAVEL PACK</small><h2>${state.hero.bag.length} ITEMS</h2></div><button id="closePack">×</button></header><div class="pack-grid">${state.hero.bag.length?state.hero.bag.map((k,i)=>itemCard(k,i)).join(''):'<p class="empty-pack">Your pack is empty.</p>'}</div></section>`;document.querySelector<HTMLButtonElement>('#closePack')!.onclick=()=>o.classList.add('hidden');o.querySelectorAll<HTMLButtonElement>('[data-use]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.use);useItem(state!,i);o.classList.add('hidden');afterAction()})}
function itemIcon(k:ItemKind){return k==='potion'?'drop':k==='bomb'?'burst':k==='ration'?'ration':k==='ward'?'ward':k==='smoke'?'smoke':'knife'}
function itemCard(k:ItemKind,i:number){const sub=k==='potion'?'+13 HP':k==='bomb'?'9 DAMAGE · NEARBY':k==='ration'?'+6 HP · +1 GUARD':k==='ward'?'+5 GUARD':k==='smoke'?'BREAK ENEMY TEMPO':'7 DAMAGE · AUTO TARGET';return `<button class="pack-item" data-use="${i}"><b class="item-icon ${itemIcon(k)}"></b><span><strong>${labelItem(k)}</strong><small>${sub}</small></span><i>USE</i></button>`}
function toggleSkill(){if(!state||state.hero.skillCooldown>0)return;skillTargeting=!skillTargeting;stopAuto();const hint=document.querySelector<HTMLElement>('#targetHint');hint?.classList.toggle('hidden',!skillTargeting);document.querySelector<HTMLButtonElement>('#skillBtn')?.classList.toggle('armed',skillTargeting);render()}
function cancelSkill(){skillTargeting=false;document.querySelector<HTMLElement>('#targetHint')?.classList.add('hidden');document.querySelector<HTMLButtonElement>('#skillBtn')?.classList.remove('armed')}

function updateHud(){if(!state)return;const hp=document.querySelector<HTMLElement>('#hpText')!,guard=document.querySelector<HTMLElement>('#guardText')!,fill=document.querySelector<HTMLElement>('#hpFill')!;hp.textContent=`${state.hero.hp} / ${state.hero.maxHp}`;guard.textContent=state.hero.guard?`GUARD ${state.hero.guard}`:'';fill.style.width=`${Math.max(0,state.hero.hp/state.hero.maxHp*100)}%`;document.querySelector<HTMLElement>('#bandName')!.textContent=BAND_NAMES[bandFor(state.floor)]??'';document.querySelector<HTMLElement>('#floorName')!.textContent=FLOOR_NAMES[state.floor]??'Unknown Floor';document.querySelector<HTMLElement>('#floorNo')!.textContent=`${String(state.floor).padStart(2,'0')} / 20`;const portrait=document.querySelector<HTMLElement>('#heroPortrait')!;portrait.className=`hero-portrait ${state.hero.cls}`;document.querySelector<HTMLElement>('#message')!.textContent=state.messages[state.messages.length-1]??'';const boss=state.enemies.find(e=>e.kind==='boss'),banner=document.querySelector<HTMLElement>('#bossBanner')!;if(boss){banner.innerHTML=`<span>${bossName(boss)}</span><div><i style="width:${Math.max(0,boss.hp/boss.maxHp*100)}%"></i></div>`;banner.classList.add('show')}else banner.classList.remove('show');
  const skill=document.querySelector<HTMLButtonElement>('#skillBtn')!,cd=document.querySelector<HTMLElement>('#skillCd')!;document.querySelector<HTMLElement>('#skillName')!.textContent=SKILL_NAMES[state.hero.cls];skill.classList.toggle('disabled',state.hero.skillCooldown>0);cd.textContent=state.hero.skillCooldown?`READY IN ${state.hero.skillCooldown}`:'READY';
  const items=document.querySelector<HTMLDivElement>('#items')!;items.innerHTML='';for(let i=0;i<4;i++){const k=state.hero.bag[i];const b=document.createElement('button');b.className='slot'+(k?' filled':'');b.innerHTML=k?`<span class="item-icon ${itemIcon(k)}"></span><small>${labelItem(k).split(' ')[0]}</small>`:`<span class="empty-dot"></span><small>EMPTY</small>`;if(k)b.onclick=()=>{cancelSkill();stopAuto();useItem(state!,i);afterAction()};items.appendChild(b)}}
function bossName(e:Unit){const b=e.bossBand??bandFor(state?.floor??1);return b===1?'WARDEN OF THE GATE':b===2?'THE IRON CAPTAIN':b===3?'THE VERDANT THRONE':b===4?'THE CURATOR': 'ECHO OF THE FIRST KING'}

function onMapTap(ev:PointerEvent){if(!state||!canvas)return;const p=screenToWorld(ev.clientX,ev.clientY);if(!p)return;const enemy=state.enemies.find(e=>e.x===p.x&&e.y===p.y);if(skillTargeting){if(enemy&&useSkill(state,p.x,p.y)){cancelSkill();afterAction()}return}if(enemy&&Math.abs(enemy.x-state.hero.x)+Math.abs(enemy.y-state.hero.y)===1){stopAuto();moveHero(state,enemy.x-state.hero.x,enemy.y-state.hero.y);afterAction();return}autoWalk(p.x,p.y)}
function screenToWorld(sx:number,sy:number){if(!state||!canvas)return null;const dpr=canvas.width/innerWidth,view=calcView(canvas),x=(sx*dpr-view.ox)/view.ts+state.hero.x,y=(sy*dpr-view.oy)/view.ts+state.hero.y;return{x:Math.floor(x),y:Math.floor(y)}}
function calcView(c:HTMLCanvasElement){const ts=Math.max(38,Math.min(60,Math.floor(Math.min(c.width/10.2,c.height/15.8))));return{ts,ox:c.width/2-ts*.5,oy:c.height*.505-ts*.5}}
function pathStep(tx:number,ty:number){if(!state)return null;const s=state;if(tx<0||ty<0||tx>=s.w||ty>=s.h)return null;const goal=ty*s.w+tx,start=s.hero.y*s.w+s.hero.x,prev=new Int32Array(s.w*s.h);prev.fill(-2);prev[start]=-1;const q=[start];for(let h=0;h<q.length;h++){const cur=q[h]!;if(cur===goal)break;const x=cur%s.w,y=Math.floor(cur/s.w);for(const[dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]] as const){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=s.w||ny>=s.h)continue;const ni=ny*s.w+nx;if(prev[ni]!==-2)continue;const t=s.tiles[ni];if(!t||['wall','void','chasm','books','pillar'].includes(t.kind))continue;if(s.enemies.some(e=>e.x===nx&&e.y===ny)&&ni!==goal)continue;prev[ni]=cur;q.push(ni)}}if(prev[goal]===-2)return null;let cur=goal;while(prev[cur]!==start&&prev[cur]>=0)cur=prev[cur]!;return{x:cur%s.w,y:Math.floor(cur/s.w)}}
function threatNear(){if(!state)return false;return state.enemies.some(e=>Math.abs(e.x-state!.hero.x)+Math.abs(e.y-state!.hero.y)<=3)}
function autoWalk(tx:number,ty:number){if(!state)return;stopAuto();const startFloor=state.floor;const tick=()=>{if(!state||state.dead||state.won||state.floor!==startFloor){stopAuto();return}const step=pathStep(tx,ty);if(!step){stopAuto();return}moveHero(state,step.x-state.hero.x,step.y-state.hero.y);afterAction();if((state.hero.x===tx&&state.hero.y===ty)||threatNear()){stopAuto();return}autoTimer=window.setTimeout(tick,82)};tick()}
function stopAuto(){if(autoTimer!==undefined){clearTimeout(autoTimer);autoTimer=undefined}}

function render(){if(!state||!canvas)return;const c=canvas.getContext('2d')!;c.imageSmoothingEnabled=false;c.clearRect(0,0,canvas.width,canvas.height);const view=calcView(canvas),band=bandFor(state.floor);drawBackdrop(c,canvas.width,canvas.height,band);for(let y=0;y<state.h;y++)for(let x=0;x<state.w;x++){const t=state.tiles[y*state.w+x];if(!t?.seen)continue;const sx=view.ox+(x-state.hero.x)*view.ts,sy=view.oy+(y-state.hero.y)*view.ts;if(sx<-view.ts||sy<-view.ts||sx>canvas.width||sy>canvas.height)continue;drawTile(c,sx,sy,view.ts,t.kind,t.variant,band,t.visible,x,y)}drawIntents(c,view);for(const d of state.drops){const t=state.tiles[d.y*state.w+d.x];if(t?.visible)drawDrop(c,view.ox+(d.x-state.hero.x)*view.ts,view.oy+(d.y-state.hero.y)*view.ts,view.ts,d.kind)}for(const e of state.enemies){const t=state.tiles[e.y*state.w+e.x];if(t?.visible)drawEnemy(c,view.ox+(e.x-state.hero.x)*view.ts,view.oy+(e.y-state.hero.y)*view.ts,view.ts,e)}drawHero(c,view.ox,view.oy,view.ts,state.hero.cls);if(skillTargeting)drawSkillRanges(c,view);drawFogEdge(c,canvas.width,canvas.height)}
function palette(b:number){if(b===1)return{floor:'#4a463d',floor2:'#575146',wall:'#242521',wall2:'#35362f',edge:'#8c806b',accent:'#b89769',shadow:'#11120f'};if(b===2)return{floor:'#3d3d38',floor2:'#4a4942',wall:'#20211f',wall2:'#323330',edge:'#80786a',accent:'#ad9060',shadow:'#10110f'};if(b===3)return{floor:'#334037',floor2:'#3f5143',wall:'#1c2923',wall2:'#2b3b31',edge:'#718e77',accent:'#c4aa67',shadow:'#0e1512'};if(b===4)return{floor:'#34343d',floor2:'#41404b',wall:'#1e1f28',wall2:'#2c2d39',edge:'#77758e',accent:'#b79b6b',shadow:'#101019'};return{floor:'#302d37',floor2:'#3e3947',wall:'#191820',wall2:'#292631',edge:'#81738c',accent:'#d2aa63',shadow:'#09080d'}}
function drawBackdrop(c:CanvasRenderingContext2D,w:number,h:number,b:number){const p=palette(b);c.fillStyle=b===5?'#06050b':'#080909';c.fillRect(0,0,w,h);const g=c.createRadialGradient(w*.5,h*.49,0,w*.5,h*.49,Math.max(w,h)*.64);g.addColorStop(0,p.wall2+'55');g.addColorStop(.52,'rgba(16,16,18,.18)');g.addColorStop(1,'rgba(0,0,0,0)');c.fillStyle=g;c.fillRect(0,0,w,h)}
function rand01(x:number,y:number,v:number){let n=(Math.imul(x+11,73856093)^Math.imul(y+17,19349663)^Math.imul(v+3,83492791))>>>0;n^=n<<13;n^=n>>>17;n^=n<<5;return(n>>>0)/4294967296}
function drawTile(c:CanvasRenderingContext2D,x:number,y:number,s:number,k:TileKind,v:number,b:number,visible:boolean,gx:number,gy:number){const p=palette(b),dim=visible?1:.34;c.save();c.globalAlpha=dim;if(k==='void'){c.restore();return}if(k==='chasm'){c.fillStyle='#030307';c.fillRect(x,y,s,s);for(let i=0;i<3;i++){const q=rand01(gx+i,gy,v+i);c.fillStyle=`rgba(170,170,205,${.08+q*.12})`;c.fillRect(x+q*s,y+rand01(gy,i,gx)*s,1.5,1.5)}c.restore();return}if(k==='wall'){c.fillStyle=p.wall;c.fillRect(x,y,s,s);c.fillStyle=p.wall2;c.fillRect(x+2,y+2,s-4,s*.64);c.fillStyle=p.shadow;c.fillRect(x,y+s*.70,s,s*.30);c.fillStyle=p.edge;c.globalAlpha*=.34;c.fillRect(x+2,y+2,s-4,2);c.fillRect(x+3,y+s*.67,s-6,2);c.globalAlpha=dim;for(let row=0;row<3;row++){const yy=y+7+row*(s*.18);const off=row%2?s*.12:0;c.strokeStyle='rgba(170,155,130,.14)';c.lineWidth=1;c.beginPath();c.moveTo(x+3,yy);c.lineTo(x+s-3,yy);c.stroke();for(let col=0;col<3;col++){const xx=x+off+col*(s*.34);c.beginPath();c.moveTo(xx,yy);c.lineTo(xx,yy+s*.15);c.stroke()}}c.restore();return}
  c.fillStyle=p.floor;c.fillRect(x,y,s,s);c.fillStyle=p.floor2;c.globalAlpha*=.25;c.fillRect(x+2,y+2,s-4,s-4);c.globalAlpha=dim;c.strokeStyle='rgba(220,215,195,.08)';c.lineWidth=1;c.beginPath();c.moveTo(x+2,y+s*.48);c.lineTo(x+s-2,y+s*.48);c.moveTo(x+s*.58,y+2);c.lineTo(x+s*.58,y+s*.48);c.moveTo(x+s*.33,y+s*.48);c.lineTo(x+s*.33,y+s-2);c.stroke();
  if(k==='door'){c.fillStyle='#3a2b20';c.fillRect(x+s*.19,y+s*.08,s*.62,s*.84);c.fillStyle='#65472d';c.fillRect(x+s*.24,y+s*.13,s*.52,s*.72);c.fillStyle='#1a140f';c.fillRect(x+s*.46,y+s*.45,s*.07,s*.09);c.strokeStyle='#a78255';c.globalAlpha*=.35;c.strokeRect(x+s*.28,y+s*.17,s*.44,s*.64)}
  else if(k==='stairs'){for(let i=0;i<5;i++){c.fillStyle=i%2?p.floor2:p.edge;c.globalAlpha=dim*(.48+i*.07);c.fillRect(x+s*.16+i*s*.035,y+s*.68-i*s*.10,s*.68-i*s*.07,s*.075)}c.globalAlpha=dim;c.fillStyle=p.accent;c.fillRect(x+s*.44,y+s*.13,s*.12,s*.26);c.beginPath();c.moveTo(x+s*.36,y+s*.22);c.lineTo(x+s*.5,y+s*.08);c.lineTo(x+s*.64,y+s*.22);c.fill()}
  else if(k==='water'){c.fillStyle=b===3?'#284f49':'#324c55';c.globalAlpha=dim*.82;c.fillRect(x+1,y+1,s-2,s-2);c.strokeStyle='rgba(153,205,195,.36)';c.lineWidth=1.5;for(let i=0;i<2;i++){const yy=y+s*(.35+i*.28);c.beginPath();c.moveTo(x+s*.12,yy);c.quadraticCurveTo(x+s*.38,yy-s*.07,x+s*.62,yy);c.quadraticCurveTo(x+s*.77,yy+s*.04,x+s*.89,yy);c.stroke()}}
  else if(k==='grass'){c.fillStyle='#39533b';c.globalAlpha=dim*.55;c.fillRect(x+1,y+1,s-2,s-2);c.strokeStyle='#718761';c.lineWidth=1.5;for(let i=0;i<5;i++){const xx=x+s*(.16+i*.16);c.beginPath();c.moveTo(xx,y+s*.78);c.lineTo(xx-s*.05,y+s*(.45+rand01(gx+i,gy,v)*.18));c.stroke()}}
  else if(k==='lava'){c.fillStyle='#421c16';c.fillRect(x+1,y+1,s-2,s-2);c.strokeStyle='#d76c38';c.lineWidth=3;c.beginPath();c.moveTo(x+s*.1,y+s*.65);c.bezierCurveTo(x+s*.32,y+s*.25,x+s*.58,y+s*.85,x+s*.9,y+s*.35);c.stroke();c.strokeStyle='#f0b25f';c.lineWidth=1;c.stroke()}
  else if(k==='books'){c.fillStyle='#221b21';c.fillRect(x+s*.09,y+s*.10,s*.82,s*.80);for(let i=0;i<4;i++){c.fillStyle=['#6d4336','#4b5b48','#63516e','#7a6541'][i]!;c.fillRect(x+s*(.17+i*.16),y+s*.18,s*.11,s*.57)}c.fillStyle='#9a805c';c.fillRect(x+s*.11,y+s*.74,s*.78,s*.06)}
  else if(k==='gear'){c.strokeStyle='#a57a4d';c.lineWidth=Math.max(2,s*.055);c.beginPath();c.arc(x+s*.5,y+s*.5,s*.22,0,Math.PI*2);c.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4;c.beginPath();c.moveTo(x+s*.5+Math.cos(a)*s*.25,y+s*.5+Math.sin(a)*s*.25);c.lineTo(x+s*.5+Math.cos(a)*s*.35,y+s*.5+Math.sin(a)*s*.35);c.stroke()}c.fillStyle='#30271e';c.beginPath();c.arc(x+s*.5,y+s*.5,s*.08,0,Math.PI*2);c.fill()}
  else if(k==='pillar'){c.fillStyle='#262722';c.beginPath();c.ellipse(x+s*.5,y+s*.76,s*.28,s*.12,0,0,Math.PI*2);c.fill();c.fillStyle='#5d594d';c.fillRect(x+s*.34,y+s*.17,s*.32,s*.56);c.fillStyle='#77705f';c.fillRect(x+s*.29,y+s*.13,s*.42,s*.11);c.fillStyle='#383a34';c.fillRect(x+s*.31,y+s*.68,s*.38,s*.10)}
  else if(k==='rubble'){c.fillStyle='#302e29';for(let i=0;i<5;i++){const q=rand01(gx+i,gy,v);c.beginPath();c.moveTo(x+s*(.15+q*.55),y+s*(.45+q*.2));c.lineTo(x+s*(.28+q*.55),y+s*(.30+q*.2));c.lineTo(x+s*(.38+q*.55),y+s*(.58+q*.15));c.closePath();c.fill()}}
  else if(k==='trap'){c.strokeStyle='rgba(160,142,112,.24)';c.lineWidth=1;c.beginPath();c.moveTo(x+s*.22,y+s*.72);c.lineTo(x+s*.5,y+s*.31);c.lineTo(x+s*.78,y+s*.72);c.closePath();c.stroke()}
  c.restore()}
function drawIntents(c:CanvasRenderingContext2D,v:{ts:number;ox:number;oy:number}){if(!state)return;for(const e of state.enemies){if(!e.intent||!state.tiles[e.y*state.w+e.x]?.visible)continue;const mark=(tx:number,ty:number,strong=false)=>{const x=v.ox+(tx-state!.hero.x)*v.ts,y=v.oy+(ty-state!.hero.y)*v.ts;c.save();c.fillStyle=strong?'rgba(214,75,53,.25)':'rgba(215,151,77,.18)';c.fillRect(x+2,y+2,v.ts-4,v.ts-4);c.strokeStyle=strong?'rgba(247,107,76,.85)':'rgba(235,180,102,.74)';c.lineWidth=2;c.strokeRect(x+3,y+3,v.ts-6,v.ts-6);c.restore()};if(e.intent==='charge'){const tx=e.intentX??state.hero.x,ty=e.intentY??state.hero.y,dx=Math.sign(tx-e.x),dy=Math.sign(ty-e.y);for(let k=1;k<=3;k++)mark(e.x+dx*k,e.y+dy*k,k===3)}else if(e.intent==='smash'){for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)if(Math.abs(dx)+Math.abs(dy)<=1)mark(e.x+dx,e.y+dy,true)}else{const tx=e.intentX??state.hero.x,ty=e.intentY??state.hero.y;if(e.intent==='curse'||e.intent==='starfire'){for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)if(Math.abs(dx)+Math.abs(dy)<=1)mark(tx+dx,ty+dy,true)}else mark(tx,ty,true)}}}
function drawDrop(c:CanvasRenderingContext2D,x:number,y:number,s:number,k:ItemKind){c.save();c.fillStyle='rgba(0,0,0,.38)';c.beginPath();c.ellipse(x+s*.5,y+s*.72,s*.22,s*.08,0,0,Math.PI*2);c.fill();const col=k==='potion'?'#d65d58':k==='bomb'?'#c78b49':k==='ration'?'#c2a86b':k==='ward'?'#a7c3c9':k==='smoke'?'#98a1a5':'#c9c2ad';c.fillStyle=col;if(k==='potion'||k==='smoke'){c.fillRect(x+s*.42,y+s*.31,s*.16,s*.08);c.beginPath();c.moveTo(x+s*.39,y+s*.38);c.lineTo(x+s*.61,y+s*.38);c.lineTo(x+s*.66,y+s*.66);c.quadraticCurveTo(x+s*.5,y+s*.76,x+s*.34,y+s*.66);c.closePath();c.fill()}else if(k==='bomb'){c.beginPath();c.arc(x+s*.5,y+s*.55,s*.17,0,Math.PI*2);c.fill();c.strokeStyle='#e2c78e';c.lineWidth=2;c.beginPath();c.moveTo(x+s*.56,y+s*.38);c.quadraticCurveTo(x+s*.68,y+s*.28,x+s*.72,y+s*.18);c.stroke()}else if(k==='ward'){c.beginPath();c.moveTo(x+s*.5,y+s*.27);c.lineTo(x+s*.69,y+s*.45);c.lineTo(x+s*.62,y+s*.69);c.lineTo(x+s*.38,y+s*.69);c.lineTo(x+s*.31,y+s*.45);c.closePath();c.fill()}else if(k==='knife'){c.fillRect(x+s*.46,y+s*.28,s*.08,s*.38);c.fillStyle='#715036';c.fillRect(x+s*.40,y+s*.63,s*.20,s*.08)}else{c.fillRect(x+s*.32,y+s*.38,s*.36,s*.28)}c.restore()}
function drawEnemy(c:CanvasRenderingContext2D,x:number,y:number,s:number,e:Unit){c.save();const cx=x+s*.5,base=y+s*.78;c.fillStyle='rgba(0,0,0,.5)';c.beginPath();c.ellipse(cx,base,s*.25,s*.08,0,0,Math.PI*2);c.fill();const elite=e.elite?1.12:1;c.translate(cx,base);c.scale(elite,elite);c.translate(-cx,-base);drawEnemyBody(c,x,y,s,e.kind,e.bossBand);if(e.elite&&e.kind!=='boss'){c.strokeStyle='#c09a5d';c.lineWidth=2;c.beginPath();c.arc(cx,y+s*.44,s*.24,Math.PI*1.05,Math.PI*1.95);c.stroke()}c.restore();if(e.hp<e.maxHp){c.fillStyle='rgba(0,0,0,.7)';c.fillRect(x+s*.18,y+s*.07,s*.64,4);c.fillStyle=e.kind==='boss'?'#d8684f':'#a84c45';c.fillRect(x+s*.18,y+s*.07,s*.64*Math.max(0,e.hp/e.maxHp),4)}}
function drawEnemyBody(c:CanvasRenderingContext2D,x:number,y:number,s:number,k:EnemyKind,bossBand?:number){const cx=x+s*.5;if(k==='rat'){c.fillStyle='#81766b';c.beginPath();c.ellipse(cx,y+s*.59,s*.24,s*.13,-.12,0,Math.PI*2);c.fill();c.beginPath();c.arc(x+s*.68,y+s*.54,s*.10,0,Math.PI*2);c.fill();c.strokeStyle='#9d8f80';c.lineWidth=2;c.beginPath();c.moveTo(x+s*.28,y+s*.60);c.quadraticCurveTo(x+s*.12,y+s*.52,x+s*.08,y+s*.68);c.stroke();return}if(k==='slime'){c.fillStyle='#668b68';c.beginPath();c.moveTo(x+s*.25,y+s*.70);c.quadraticCurveTo(x+s*.22,y+s*.37,cx,y+s*.31);c.quadraticCurveTo(x+s*.79,y+s*.42,x+s*.75,y+s*.70);c.closePath();c.fill();c.fillStyle='#b9d4a4';c.fillRect(x+s*.38,y+s*.49,3,3);c.fillRect(x+s*.59,y+s*.49,3,3);return}if(k==='hound'){c.fillStyle='#756758';c.beginPath();c.ellipse(x+s*.48,y+s*.59,s*.24,s*.15,0,0,Math.PI*2);c.fill();c.beginPath();c.moveTo(x+s*.62,y+s*.51);c.lineTo(x+s*.80,y+s*.43);c.lineTo(x+s*.74,y+s*.62);c.closePath();c.fill();for(const lx of [.35,.55,.66])c.fillRect(x+s*lx,y+s*.64,3,s*.15);return}if(k==='wisp'){const g=c.createRadialGradient(cx,y+s*.46,1,cx,y+s*.46,s*.24);g.addColorStop(0,'#eff7df');g.addColorStop(.35,'#9bc6c0');g.addColorStop(1,'rgba(95,141,144,0)');c.fillStyle=g;c.beginPath();c.arc(cx,y+s*.46,s*.25,0,Math.PI*2);c.fill();return}const robe=k==='cultist'||k==='seer',heavy=k==='guard'||k==='knight'||k==='golem'||k==='boss';let body=robe?'#5f5168':k==='archer'?'#52644f':k==='golem'?'#6e6557':heavy?'#6d706d':'#665d56';if(k==='boss')body=bossBand===3?'#55704f':bossBand===5?'#665b79':'#766658';c.fillStyle=body;if(k==='golem'){c.fillRect(x+s*.28,y+s*.31,s*.44,s*.39);c.fillRect(x+s*.20,y+s*.42,s*.12,s*.28);c.fillRect(x+s*.68,y+s*.42,s*.12,s*.28);c.fillStyle='#312f2b';c.fillRect(x+s*.38,y+s*.22,s*.24,s*.14)}else{c.beginPath();c.arc(cx,y+s*.30,s*(k==='boss'?.14:.11),0,Math.PI*2);c.fill();c.beginPath();c.moveTo(x+s*(robe?.34:.31),y+s*.40);c.lineTo(x+s*(robe?.25:.28),y+s*.73);c.lineTo(x+s*(robe?.75:.72),y+s*.73);c.lineTo(x+s*(robe?.66:.69),y+s*.40);c.closePath();c.fill()}if(k==='guard'||k==='knight'||k==='boss'){c.fillStyle='#3b403f';c.beginPath();c.moveTo(x+s*.20,y+s*.43);c.lineTo(x+s*.34,y+s*.39);c.lineTo(x+s*.34,y+s*.68);c.lineTo(x+s*.20,y+s*.62);c.closePath();c.fill();c.strokeStyle='#b2a070';c.lineWidth=2;c.beginPath();c.moveTo(x+s*.72,y+s*.38);c.lineTo(x+s*.79,y+s*.73);c.stroke()}if(k==='archer'){c.strokeStyle='#b79c70';c.lineWidth=2;c.beginPath();c.arc(x+s*.70,y+s*.50,s*.18,-Math.PI/2,Math.PI/2);c.stroke();c.beginPath();c.moveTo(x+s*.69,y+s*.32);c.lineTo(x+s*.69,y+s*.68);c.stroke()}if(k==='seer'||k==='cultist'){c.fillStyle=k==='seer'?'#b8c8c2':'#b1959e';c.fillRect(x+s*.46,y+s*.27,s*.08,s*.05)}}
function drawHero(c:CanvasRenderingContext2D,x:number,y:number,s:number,cls:HeroClass){c.save();c.fillStyle='rgba(0,0,0,.58)';c.beginPath();c.ellipse(x+s*.5,y+s*.80,s*.27,s*.09,0,0,Math.PI*2);c.fill();const col=cls==='vanguard'?'#c7b49a':cls==='ranger'?'#8fa37e':'#9787b3';c.fillStyle='#d4b08d';c.beginPath();c.arc(x+s*.5,y+s*.30,s*.12,0,Math.PI*2);c.fill();c.fillStyle=col;c.beginPath();c.moveTo(x+s*.31,y+s*.42);c.lineTo(x+s*.25,y+s*.75);c.lineTo(x+s*.75,y+s*.75);c.lineTo(x+s*.69,y+s*.42);c.closePath();c.fill();if(cls==='vanguard'){c.fillStyle='#525856';c.beginPath();c.moveTo(x+s*.18,y+s*.45);c.lineTo(x+s*.33,y+s*.39);c.lineTo(x+s*.35,y+s*.69);c.lineTo(x+s*.18,y+s*.63);c.closePath();c.fill();c.strokeStyle='#d3bd87';c.lineWidth=2;c.beginPath();c.moveTo(x+s*.72,y+s*.37);c.lineTo(x+s*.79,y+s*.74);c.stroke()}else if(cls==='ranger'){c.strokeStyle='#d0b17a';c.lineWidth=2;c.beginPath();c.arc(x+s*.72,y+s*.51,s*.19,-Math.PI/2,Math.PI/2);c.stroke()}else{c.strokeStyle='#c4b4df';c.lineWidth=2;c.beginPath();c.moveTo(x+s*.72,y+s*.35);c.lineTo(x+s*.77,y+s*.73);c.stroke();c.fillStyle='#d8c5ef';c.beginPath();c.arc(x+s*.71,y+s*.33,s*.05,0,Math.PI*2);c.fill()}c.restore()}
function drawSkillRanges(c:CanvasRenderingContext2D,v:{ts:number;ox:number;oy:number}){if(!state)return;for(const e of state.enemies){const d=Math.abs(e.x-state.hero.x)+Math.abs(e.y-state.hero.y),ok=state.hero.cls==='vanguard'?d===1:d<= (state.hero.cls==='ranger'?6:5);if(!ok||!state.tiles[e.y*state.w+e.x]?.visible)continue;const x=v.ox+(e.x-state.hero.x)*v.ts,y=v.oy+(e.y-state.hero.y)*v.ts;c.strokeStyle='rgba(231,205,131,.92)';c.lineWidth=2;c.strokeRect(x+3,y+3,v.ts-6,v.ts-6)}}
function drawFogEdge(c:CanvasRenderingContext2D,w:number,h:number){const g=c.createRadialGradient(w*.5,h*.50,Math.min(w,h)*.20,w*.5,h*.50,Math.max(w,h)*.68);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(.62,'rgba(0,0,0,.08)');g.addColorStop(1,'rgba(0,0,0,.70)');c.fillStyle=g;c.fillRect(0,0,w,h)}

function drawTitleArt(){if(!titleCanvas)return;const c=titleCanvas.getContext('2d')!,dpr=Math.min(2,devicePixelRatio||1),w=Math.floor(innerWidth*dpr),h=Math.floor(innerHeight*dpr);titleCanvas.width=w;titleCanvas.height=h;c.clearRect(0,0,w,h);const sky=c.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#181a20');sky.addColorStop(.46,'#0d0f13');sky.addColorStop(1,'#050607');c.fillStyle=sky;c.fillRect(0,0,w,h);const moon=c.createRadialGradient(w*.73,h*.18,0,w*.73,h*.18,w*.20);moon.addColorStop(0,'rgba(220,218,197,.18)');moon.addColorStop(.24,'rgba(168,167,153,.08)');moon.addColorStop(1,'rgba(0,0,0,0)');c.fillStyle=moon;c.fillRect(0,0,w,h);for(let i=0;i<34;i++){const x=((i*73)%100)/100*w,y=((i*41)%37)/100*h;c.fillStyle=`rgba(210,214,218,${.05+(i%5)*.02})`;c.fillRect(x,y,Math.max(1,dpr),Math.max(1,dpr))}
  const baseY=h*.72,center=w*.50,levels=[{y:baseY,w:w*.52,h:h*.15},{y:h*.59,w:w*.42,h:h*.15},{y:h*.47,w:w*.33,h:h*.14},{y:h*.36,w:w*.25,h:h*.13},{y:h*.26,w:w*.18,h:h*.12}];for(const [n,L] of levels.entries()){const x=center-L.w/2;c.fillStyle=n%2?'#15171a':'#121417';c.fillRect(x,L.y,L.w,L.h);c.fillStyle='rgba(90,92,91,.16)';c.fillRect(x+L.w*.06,L.y+L.h*.08,L.w*.88,2*dpr);const butt=L.w*.07;c.fillStyle='#0b0c0e';c.beginPath();c.moveTo(x,L.y+L.h);c.lineTo(x-butt,L.y+L.h);c.lineTo(x,L.y+L.h*.18);c.closePath();c.fill();c.beginPath();c.moveTo(x+L.w,L.y+L.h);c.lineTo(x+L.w+butt,L.y+L.h);c.lineTo(x+L.w,L.y+L.h*.18);c.closePath();c.fill();for(let j=0;j<Math.max(2,6-n);j++){const wx=x+L.w*(.15+j/(Math.max(2,5-n))*.70);c.fillStyle=j%3===0?'rgba(197,161,94,.20)':'rgba(115,119,116,.12)';c.fillRect(wx,L.y+L.h*.34,3*dpr,8*dpr)}}c.fillStyle='#0d0e11';c.fillRect(center-w*.055,h*.18,w*.11,h*.10);c.beginPath();c.moveTo(center-w*.065,h*.18);c.lineTo(center-w*.035,h*.18);c.lineTo(center,h*.135);c.lineTo(center+w*.035,h*.18);c.lineTo(center+w*.065,h*.18);c.lineTo(center+w*.055,h*.20);c.lineTo(center-w*.055,h*.20);c.closePath();c.fill();const mist=c.createLinearGradient(0,h*.58,0,h);mist.addColorStop(0,'rgba(126,133,132,0)');mist.addColorStop(.35,'rgba(126,133,132,.06)');mist.addColorStop(1,'rgba(5,6,7,.82)');c.fillStyle=mist;c.fillRect(0,h*.5,w,h*.5)}

showTitle();
